import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { transferableAbortController } from 'node:util'
import { createMemoryRouter, RouterProvider } from 'react-router-dom'
import { onlineManager, QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import type { LeaveContext } from '../../src/lib/leave/contracts'
import { employeeA, employeeB, managerA, directorA, hrA } from './fixtures'
const mocks = vi.hoisted(() => ({listeners:new Set<()=>void>(),rpc:vi.fn(),auth:{user:{id:'71000000-0000-0000-0000-000000000001'},profile:{id:'71000000-0000-0000-0000-000000000001',is_active:true,role:'sales_person',full_name:'Fictional actor'},loading:false,signOut:vi.fn()}}))
vi.mock('../../src/lib/supabase',()=>({supabase:{rpc:mocks.rpc}}))
vi.mock('../../src/lib/AuthContext',async()=>{const {useEffect,useReducer}=await import('react');return {useAuth:()=>{const [,update]=useReducer(n=>n+1,0);useEffect(()=>{mocks.listeners.add(update);return()=>{mocks.listeners.delete(update)}},[]);return mocks.auth}}})
import LeaveManagement from '../../src/pages/ihr/LeaveManagement'
import { leaveKeys } from '../../src/lib/leave/queryKeys'
const scope='integration-scope',requestId='82000000-0000-0000-0000-000000000001'
const none={request:false,approve:false,configure:false,adjust:false,readPrivate:false,manageAccess:false}
const personal:LeaveContext={scopeVersion:scope,memberKind:'employee',capabilities:{...none,request:true},setup:{ready:false,blockers:[]},balances:[],timezone:'Etc/UTC',currentPeriod:{year:2026,startDate:'2026-01-01',endDate:'2027-01-01'}}
const summary={id:requestId,sequence:1,startDate:'2026-10-09',endDate:'2026-10-09',duration:{mode:'full_scheduled_day'},totalMinutes:450,status:'submitted',version:1,submittedAt:'2026-10-03T00:00:00Z',sourceKind:'submission',employee:{id:employeeA,name:'Fictional employee'},cancellationAttemptId:null,cancellationRequestedAt:null}
const detail={...summary,reason:'Fictional private reason',approverName:'Fictional manager',days:[{date:'2026-10-09',scheduledMinutes:450,chargedMinutes:450,exclusion:null,groupName:null}],allocations:[{year:2026,startDate:'2026-01-01',endDate:'2027-01-01',chargedMinutes:450}],cancellation:null,balanceContext:{basis:'current',asOf:'2026-10-03T01:00:00Z',periods:[{year:2026,reservedMinutes:450,usedMinutes:900,availableMinutes:4050,expiredMinutes:0,reconciled:true}]}}
const settings={employeeId:employeeA,authorityKey:'a'.repeat(64),memberVersion:2,policy:null,policyDrafts:[],governance:[],readiness:{ready:false,blockers:[{code:'RETENTION_UNCONFIRMED',message:'Retensi belum disetujui'}]},impacts:{available:false,pendingCount:null,approvedCount:null}}
let ownRows:any[]
let context:LeaveContext, audiences:string[], targets:any[], rows:any[], counts:{pendingLeave:number;pendingCancellation:number}
let pausedContext=false, rejectContext=false, pendingSignals:AbortSignal[],finishMutation:((value:any)=>void)|undefined
const clients:QueryClient[]=[],routers:ReturnType<typeof createMemoryRouter>[]=[]
function response(name:string,args:any={}){
 if(name==='leave_context_v1')return context
 if(name==='leave_reads_context_v1')return {scopeVersion:context.scopeVersion,calendarAudiences:audiences,defaultRange:{from:'2026-10-01',to:'2026-10-31'},defaultRangeState:'ready'}
 if(name==='leave_calendar_v1')return [{employeeId:employeeA,employeeName:'Fictional calendar employee',date:'2026-10-09',approvedMinutes:450,availabilityLabel:'full_scheduled_absence'}]
 if(name==='leave_approval_counts_v1')return counts
 if(name==='leave_assigned_inbox_v1')return {rows,nextBefore:null}
 if(name==='leave_assigned_request_v1')return detail
 if(name==='leave_admin_targets_v1')return {rows:targets,total:targets.length,page:args.p_page,pageSize:args.p_page_size}
 if(name==='leave_hr_requests_v1'){const {employee,cancellationAttemptId,cancellationRequestedAt,...own}=summary;return {employeeId:args.p_employee_id,scopeVersion:context.scopeVersion,authorityKey:'a'.repeat(64),rows:[own],nextBefore:null}}
 if(name==='leave_hr_request_v1'){const {employee,cancellationAttemptId,cancellationRequestedAt,cancellation,balanceContext,...own}=detail;return {employeeId:args.p_employee_id,scopeVersion:context.scopeVersion,authorityKey:'a'.repeat(64),request:own}}
 if(name==='leave_hr_request_history_v1'){const old=!!args.p_before_at;const row={id:old?'84000000-0000-0000-0000-000000000002':'84000000-0000-0000-0000-000000000001',event:'rejected',atTime:old?'2026-10-02T10:00:00Z':'2026-10-03T10:00:00Z',actor:{id:managerA,name:'Fictional reviewer'},reason:old?'Fictional older event':'Fictional event reason',approverName:null};return {employeeId:args.p_employee_id,requestId:args.p_request_id,scopeVersion:context.scopeVersion,authorityKey:'a'.repeat(64),rows:[row],nextBefore:old?null:{atTime:row.atTime,id:row.id}}}
 if(name==='leave_balance_accounts_v1')return {currentPeriod:personal.currentPeriod,balances:[{accountId:employeeB,year:2026,allowanceMinutes:5400,approvedMinutes:450,pendingMinutes:0,availableMinutes:4950,expiredMinutes:0,version:2,reconciled:true}]}
 if(name==='leave_balance_history_v1')return {balance:response('leave_balance_accounts_v1').balances[0],rows:[{id:employeeA,sequence:1,date:'2026-10-02',kind:'adjustment',allowanceDelta:60,reservedDelta:0,usedDelta:0}],nextBefore:null}
 if(name==='leave_admin_write_context_v1')return {employeeId:args.p_employee_id,scopeVersion:context.scopeVersion,authorityKey:'a'.repeat(64),capabilities:{configure:context.capabilities.configure,adjust:context.capabilities.adjust},balance:{state:'verified',currentPeriod:personal.currentPeriod,account:{accountId:employeeB,year:2026,version:2,reconciled:true}},memberOptions:context.capabilities.configure?{state:'available',calendars:[{id:employeeB,name:'Fictional current lineage'}],groups:[]}:null}
 if(name==='leave_admin_setup_v1')return {rows:args.p_section==='members'?[{id:employeeA,name:'Fictional target',memberKind:'employee',active:true,employmentStart:'2020-01-01',eligibilityDate:'2021-01-01',calendarId:employeeB,version:1,impacts:{available:false,pendingCount:null,approvedCount:null},assignments:[],memberships:[]}]:[],total:args.p_section==='members'?1:0,page:args.p_page,pageSize:args.p_page_size}
 if(name==='leave_admin_settings_v1')return {...settings,employeeId:args.p_employee_id}
 if(name==='leave_admin_access_v1')return {employeeId:args.p_employee_id,authorityKey:'a'.repeat(64),grants:[],manifests:[]}
 if(name==='leave_admin_requests_v1')return {rows:[],nextBefore:null}
 if(name==='leave_own_history_v1')return {rows:ownRows,nextBefore:null}
 if(name==='leave_own_request_history_v1')return {requestId:args.p_request_id,requestVersion:1,scopeVersion:context.scopeVersion,rows:[],nextBefore:null}
 if(name==='leave_own_request_v1'){const {employee,cancellationAttemptId,cancellationRequestedAt,cancellation,balanceContext,...own}=detail;return own}
 if(name==='leave_request_transition_state_v1')return {id:requestId,version:1,status:'submitted',canWithdraw:true,canRequestCancellation:false,cancellationBlocker:null,activeAttemptId:null}
 throw new Error('Unexpected fixture RPC '+name)
}
function serve(){mocks.rpc.mockImplementation((name:string,args:any)=>{
 if(mocks.rpc.mock.calls.length>50)throw new Error('Fixture request budget exceeded')
 if(name==='leave_transaction_v1')return new Promise(resolve=>{finishMutation=resolve})
 return {abortSignal:(signal:AbortSignal)=>{
  if(name==='leave_context_v1'&&pausedContext){pendingSignals.push(signal);return new Promise(()=>{})}
  if(name==='leave_context_v1'&&rejectContext)return Promise.reject(new Error('Private diagnostic'))
  return Promise.resolve({data:response(name,args),error:null})
 }}
})}
function identity(id:string){mocks.auth.user.id=id;mocks.auth.profile.id=id}
function mount(client=new QueryClient({defaultOptions:{queries:{retry:false}}})){clients.push(client);const router=createMemoryRouter([{path:'/ihr/leave',element:<LeaveManagement/>},{path:'/away',element:<p>Other page</p>}],{initialEntries:['/ihr/leave']});routers.push(router);const element=()=> <QueryClientProvider client={client}><RouterProvider router={router}/></QueryClientProvider>;const view=render(element());return {client,router,view,element}}
function guarded(){const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented}
function tab(name:string){return screen.getByRole('tab',{name:new RegExp(name)})}
beforeEach(()=>{vi.stubGlobal('AbortController',class{constructor(){return transferableAbortController()}});identity(employeeA);mocks.auth.profile.role='sales_person';mocks.auth.profile.is_active=true;context=personal;audiences=['own'];ownRows=[];targets=[];rows=[summary];counts={pendingLeave:1,pendingCancellation:2};pausedContext=false;rejectContext=false;pendingSignals=[];finishMutation=undefined;localStorage.clear();onlineManager.setOnline(true);vi.spyOn(window,'confirm').mockReturnValue(false);serve()})
afterEach(()=>{cleanup();routers.splice(0).forEach(r=>r.dispose());clients.splice(0).forEach(c=>c.clear());onlineManager.setOnline(true);vi.restoreAllMocks();vi.unstubAllGlobals();mocks.rpc.mockReset();mocks.auth.signOut.mockClear()})
test('employee navigates between real own history and authorized own calendar without duplicate private owners',async()=>{
 mount();await screen.findByRole('tab',{name:'Cuti Saya'});fireEvent.click(await screen.findByRole('button',{name:'Riwayat pengajuan'}));await screen.findByText('Belum ada pengajuan cuti.')
 fireEvent.click(tab('Kalender'));expect(await screen.findByText('Fictional calendar employee')).toBeTruthy();expect(screen.queryByRole('button',{name:'Buat pratinjau cuti'})).toBeNull();expect(screen.queryByRole('tab',{name:/Persetujuan/})).toBeNull()
 expect(screen.getByRole('tabpanel').getAttribute('aria-labelledby')).toBe(tab('Kalender').id)
 fireEvent.click(tab('Cuti Saya'));expect(await screen.findByRole('button',{name:'Buat pratinjau cuti'})).toBeTruthy()
})
test('assigned manager gets full count, opens detail, guards tab and router departure, then decides and refreshes counts',async()=>{
 identity(managerA);context={...personal,memberKind:'manager',capabilities:{...none,request:true,approve:true}};audiences=['own','assigned_team'];const {router}=mount()
 fireEvent.click(await screen.findByRole('tab',{name:/Persetujuan/}));expect(await screen.findByLabelText('3 persetujuan menunggu')).toBeTruthy();fireEvent.click(await screen.findByRole('button',{name:'Tinjau Fictional employee'}));fireEvent.change(await screen.findByLabelText('Alasan penolakan'),{target:{value:'Private decision draft'}})
 fireEvent.click(tab('Kalender'));expect(await screen.findByDisplayValue('Private decision draft')).toBeTruthy();expect(guarded()).toBe(true)
 await act(async()=>{void router.navigate('/away')});expect(router.state.location.pathname).toBe('/ihr/leave')
 fireEvent.click(screen.getByRole('button',{name:'Tolak cuti'}));await waitFor(()=>expect(finishMutation).toBeDefined());rows=[];counts={pendingLeave:0,pendingCancellation:0};await act(async()=>finishMutation!({data:{id:requestId,version:2,operation:'reject_request'},error:null}))
 expect(await screen.findByText('Keputusan tersimpan.')).toBeTruthy();expect(await screen.findByLabelText('0 persetujuan menunggu')).toBeTruthy();expect(screen.queryByDisplayValue('Private decision draft')).toBeNull()
})
test('director sees only assigned approval and minimal assigned-manager calendar, never personal entitlement or HR settings',async()=>{
 identity(directorA);context={...personal,memberKind:'director',balances:[],currentPeriod:null,timezone:null,capabilities:{...none,approve:true}};audiences=['assigned_team'];mount()
 expect(await screen.findByRole('button',{name:'Tinjau Fictional employee'})).toBeTruthy();expect(screen.queryByRole('tab',{name:'Cuti Saya'})).toBeNull();expect(screen.queryByRole('tab',{name:'Pengaturan'})).toBeNull();fireEvent.click(tab('Kalender'));await screen.findByText('Fictional calendar employee')
 expect(screen.queryByRole('option',{name:'Cuti saya'})).toBeNull();expect(screen.queryByRole('option',{name:'Akses kalender yang diberikan'})).toBeNull();expect(mocks.rpc.mock.calls.some(([name])=>name==='leave_balance_accounts_v1'||name==='leave_own_history_v1'||name==='leave_admin_targets_v1')).toBe(false)
})
test('configure-only discovers exact targets and exposes policy without approval/private balance/access controls',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional configured target',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];mount()
 fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional configured target'}));expect(await screen.findByLabelText('Alasan policy')).toBeTruthy();expect(screen.queryByLabelText('Manifest izin yang disetujui')).toBeNull();expect(screen.queryByLabelText('Permohonan yang dialihkan')).toBeNull();expect(screen.queryByRole('tab',{name:/Persetujuan/})).toBeNull();expect(mocks.rpc.mock.calls.some(([name])=>name==='leave_balance_accounts_v1')).toBe(false)
})
test('calendar-only grant is discovered independently of personal, approval and configuration capabilities',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:none,balances:[],currentPeriod:null};audiences=['granted'];mount();fireEvent.click(await screen.findByRole('tab',{name:/Kalender/}));expect(await screen.findByText('Fictional calendar employee')).toBeTruthy();expect(screen.queryByRole('tab',{name:'Pengaturan'})).toBeNull();expect(screen.queryByRole('tab',{name:/Persetujuan/})).toBeNull()
})
test('settings draft stays hidden and guarded after canceled offline context, then target and actor replacement erase it',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional target A',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}},{id:employeeB,name:'Fictional target B',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];const {client,view,element}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target A'}));fireEvent.change(await screen.findByLabelText('Alasan policy'),{target:{value:'Private admin draft'}});expect(guarded()).toBe(true)
 onlineManager.setOnline(false);pausedContext=true;fireEvent(window,new Event('focus'));await waitFor(()=>expect(pendingSignals.length).toBeGreaterThan(0));await act(async()=>client.cancelQueries({queryKey:leaveKeys.context(hrA,'current'),exact:true}));expect(screen.queryByDisplayValue('Private admin draft')).toBeNull();expect(guarded()).toBe(true)
 onlineManager.setOnline(true);pausedContext=false;fireEvent.click(await screen.findByRole('button',{name:'Coba lagi'}));expect(await screen.findByDisplayValue('Private admin draft')).toBeTruthy()
 vi.mocked(window.confirm).mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Kembali ke daftar anggota'}));fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target B'}));expect((await screen.findByLabelText('Alasan policy') as HTMLTextAreaElement).value).toBe('')
 fireEvent.change(screen.getByLabelText('Alasan policy'),{target:{value:'Other private draft'}});identity(employeeB);context=personal;await act(async()=>mocks.listeners.forEach(update=>update()));view.rerender(element());expect(screen.queryByDisplayValue('Other private draft')).toBeNull();expect(guarded()).toBe(false)
})

test('whole page has bounded reads on entry, calendar tab, focus, reconnect and canceled authority recovery',async()=>{
 identity(managerA);context={...personal,memberKind:'manager',capabilities:{...none,request:true,approve:true}};audiences=['own','assigned_team'];const {client}=mount()
 await screen.findByLabelText('3 persetujuan menunggu')
 const entryCalls=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(entryCalls);expect(entryCalls).toBeLessThanOrEqual(3)
 fireEvent.click(tab('Kalender'));await screen.findByText('Fictional calendar employee');const calendarCalls=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(calendarCalls);expect(calendarCalls-entryCalls).toBeLessThanOrEqual(4)
 fireEvent(window,new Event('focus'));await screen.findByText('Fictional calendar employee');await waitFor(()=>expect(client.isFetching()).toBe(0));const focusCalls=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(focusCalls);expect(focusCalls-calendarCalls).toBeLessThanOrEqual(5)
 await act(async()=>onlineManager.setOnline(false));await act(async()=>onlineManager.setOnline(true));await waitFor(()=>expect(client.isFetching()).toBe(0));const reconnectCalls=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(reconnectCalls);expect(reconnectCalls-focusCalls).toBeLessThanOrEqual(5)
 pausedContext=true;fireEvent(window,new Event('focus'));await waitFor(()=>expect(pendingSignals.length).toBeGreaterThan(0));await act(async()=>client.cancelQueries({queryKey:leaveKeys.context(managerA,'current'),exact:true}));expect(screen.queryByText('Fictional calendar employee')).toBeNull();const cancelCalls=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(cancelCalls)
 pausedContext=false;fireEvent.click(within(screen.getByText('Akses cuti belum dapat dikonfirmasi. Silakan coba lagi.').closest('[role=alert]') as HTMLElement).getByRole('button',{name:'Coba lagi'}));await waitFor(()=>expect(client.isFetching()).toBe(0));const retries=screen.queryAllByRole('button',{name:'Coba lagi'});if(retries.length)fireEvent.click(retries[0]);await screen.findByText('Fictional calendar employee');const recoveredCalls=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(recoveredCalls);expect(recoveredCalls-cancelCalls).toBeLessThanOrEqual(7)
})

test('adjust-only opens minimal verified account and sends adjustment without reading private amounts',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,adjust:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional adjust target',capabilities:{configure:false,adjust:true,readPrivate:false,calendar:false,manageAccess:false}}];mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional adjust target'}));fireEvent.change(await screen.findByLabelText('ID sumber'),{target:{value:'83000000-0000-0000-0000-000000000001'}});fireEvent.change(screen.getByLabelText('Alasan'),{target:{value:'Approved adjustment'}});fireEvent.change(screen.getByLabelText('Menit penyesuaian'),{target:{value:'60'}});fireEvent.click(screen.getByRole('button',{name:'Simpan penyesuaian'}));await waitFor(()=>expect(finishMutation).toBeDefined());expect(mocks.rpc.mock.calls.some(([name])=>name==='leave_balance_accounts_v1'||name==='leave_balance_history_v1'||name==='leave_admin_settings_v1')).toBe(false)
 await act(async()=>finishMutation!({data:{id:employeeB,version:3,operation:'adjust_balance'},error:null}));expect(await screen.findByText('Saldo tersimpan. Muat ulang untuk meninjau versi terbaru.')).toBeTruthy()
})
test('scoped configure opens only current member lineage options and guards private panel changes',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional configured target',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional configured target'}));await screen.findByLabelText('Alasan policy');fireEvent.click(screen.getByRole('button',{name:'Keanggotaan'}));expect(await screen.findByRole('option',{name:'Fictional current lineage'})).toBeTruthy();expect(mocks.rpc.mock.calls.some(([name,args])=>name==='leave_admin_setup_v1'&&args.p_section==='rota')).toBe(false)
 fireEvent.change(screen.getByLabelText('Alasan perubahan'),{target:{value:'Private membership draft'}});fireEvent.click(screen.getByRole('button',{name:'Kebijakan dan akses'}));expect(screen.getByDisplayValue('Private membership draft')).toBeTruthy();vi.mocked(window.confirm).mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Kebijakan dan akses'}));expect(await screen.findByLabelText('Alasan policy')).toBeTruthy();expect(screen.queryByDisplayValue('Private membership draft')).toBeNull()
})

test('two real page observers refresh assigned inbox and counts after one decision without deleting the other observer',async()=>{
 identity(managerA);context={...personal,memberKind:'manager',capabilities:{...none,request:true,approve:true}};audiences=['own','assigned_team'];const {client,view:first}=mount();const second=mount(client).view
 for(const view of [first,second])fireEvent.click(await within(view.container).findByRole('tab',{name:'Persetujuan'}))
 await within(second.container).findByRole('button',{name:'Tinjau Fictional employee'});fireEvent.click(await within(first.container).findByRole('button',{name:'Tinjau Fictional employee'}));fireEvent.click(await within(first.container).findByRole('button',{name:'Setujui cuti'}));await waitFor(()=>expect(finishMutation).toBeDefined());rows=[];counts={pendingLeave:0,pendingCancellation:0};await act(async()=>finishMutation!({data:{id:requestId,version:2,operation:'approve_request'},error:null}))
 expect(await within(second.container).findByText('Tidak ada permintaan yang menunggu keputusan.')).toBeTruthy();expect(await within(second.container).findByLabelText('0 persetujuan menunggu')).toBeTruthy();first.unmount();expect(within(second.container).getByText('Tidak ada permintaan yang menunggu keputusan.')).toBeTruthy();const settled=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(settled);expect(settled).toBeLessThanOrEqual(22)
})
test.each(['leave_assigned_inbox_v1','leave_approval_counts_v1','leave_reads_context_v1','leave_calendar_v1'])('whole page %s failure terminates within bounded reads and explicit retry restores current data',async failed=>{
 identity(managerA);context={...personal,memberKind:'manager',capabilities:{...none,request:true,approve:true}};audiences=['own','assigned_team'];let failing=true
 const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name===failed&&failing?{abortSignal:()=>Promise.resolve({data:null,error:{code:'55000'}})}:normal(name,args))
 const {client}=mount();fireEvent.click(await screen.findByRole('tab',{name:failed.includes('assigned')?'Persetujuan':'Kalender'}));await waitFor(()=>expect(mocks.rpc.mock.calls.some(([name])=>name===failed)).toBe(true));if(failed==='leave_approval_counts_v1')await screen.findByText('Fictional calendar employee');else await screen.findByText(failed==='leave_assigned_inbox_v1'?'Daftar persetujuan belum dapat dimuat. Coba muat ulang daftar.':failed==='leave_reads_context_v1'?'Akses kalender belum dapat dikonfirmasi.':'Kalender belum dapat dimuat.');await waitFor(()=>expect(client.isFetching()).toBe(0));const stopped=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,40))});expect(mocks.rpc.mock.calls.length).toBe(stopped);expect(stopped).toBeLessThanOrEqual(9)
 failing=false;fireEvent(window,new Event('focus'));await waitFor(()=>expect(client.isFetching()).toBe(0));if(failed.includes('assigned'))expect(await screen.findByRole('button',{name:'Tinjau Fictional employee'})).toBeTruthy();else expect(await screen.findByText('Fictional calendar employee')).toBeTruthy();const recovered=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(recovered);expect(recovered-stopped).toBeLessThanOrEqual(8)
})
test('narrow navigation wraps and uses one selected tab with keyboard focus and associated panel',async()=>{
 Object.defineProperty(window,'innerWidth',{configurable:true,value:320});identity(managerA);context={...personal,memberKind:'manager',capabilities:{...none,request:true,approve:true}};audiences=['own','assigned_team'];mount();await screen.findByLabelText('3 persetujuan menunggu');const list=screen.getByRole('tablist');expect(list.className).toContain('flex-wrap');expect(screen.getAllByRole('tab').filter(t=>t.getAttribute('tabindex')==='0')).toHaveLength(1)
 tab('Cuti Saya').focus();fireEvent.keyDown(tab('Cuti Saya'),{key:'ArrowRight'});expect(document.activeElement).toBe(tab('Persetujuan'));expect(tab('Cuti Saya').getAttribute('aria-selected')).toBe('true');fireEvent.click(tab('Persetujuan'));await screen.findByRole('button',{name:'Tinjau Fictional employee'});expect(screen.getByRole('tabpanel').getAttribute('aria-labelledby')).toBe(tab('Persetujuan').id);expect(screen.getByRole('tabpanel').className).toContain('min-w-0')
})

test('scoped configuration cannot manufacture global rota options, and failed discovery stays bounded',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[];const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_setup_v1'&&args.p_section==='rota'?{abortSignal:()=>Promise.resolve({data:null,error:{code:'42501'}})}:normal(name,args));const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Kalender dan roster perusahaan'}));expect(await screen.findByText('Kalender dan roster memerlukan izin konfigurasi global yang dikonfirmasi.')).toBeTruthy();expect(screen.queryByLabelText('Nama kalender')).toBeNull();await waitFor(()=>expect(client.isFetching()).toBe(0));const stopped=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,35))});expect(mocks.rpc.mock.calls.length).toBe(stopped);expect(stopped).toBeLessThanOrEqual(6)
})

test.each(['leave_own_history_v1','leave_own_request_v1','leave_request_transition_state_v1'])('own %s failure has bounded reads and an explicit fresh retry',async failed=>{
 const {employee,cancellationAttemptId,cancellationRequestedAt,...own}=summary;ownRows=[own];let failing=true;const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name===failed&&failing?{abortSignal:()=>Promise.resolve({data:null,error:{code:'55000'}})}:normal(name,args));const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Riwayat pengajuan'}))
 if(failed!=='leave_own_history_v1')fireEvent.click(await screen.findByRole('button',{name:'Lihat rincian 2026-10-09 sampai 2026-10-09'}))
 const retry=failed==='leave_own_history_v1'?'Coba lagi riwayat pengajuan':failed==='leave_own_request_v1'?'Coba lagi rincian':'Coba lagi tindakan';await screen.findByRole('button',{name:retry});await waitFor(()=>expect(client.isFetching()).toBe(0));const stopped=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,40))});expect(mocks.rpc.mock.calls.length).toBe(stopped);expect(stopped).toBeLessThanOrEqual(12)
 failing=false;fireEvent.click(screen.getByRole('button',{name:retry}));if(failed==='leave_own_history_v1')await screen.findByRole('button',{name:'Lihat rincian 2026-10-09 sampai 2026-10-09'});else await screen.findByRole('button',{name:'Tarik pengajuan'});await waitFor(()=>expect(client.isFetching()).toBe(0));const recovered=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(recovered);expect(recovered-stopped).toBeLessThanOrEqual(10)
})
test.each(['leave_admin_targets_v1','leave_admin_settings_v1','leave_admin_write_context_v1','leave_admin_setup_v1'])('admin %s read failure stops, keeps private controls unavailable and supports a fresh retry',async failed=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional target',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];let failing=true;const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name===failed&&failing?{abortSignal:()=>Promise.resolve({data:null,error:{code:'55000'}})}:normal(name,args));const {client}=mount()
 if(failed!=='leave_admin_targets_v1')fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target'}))
 if(failed==='leave_admin_write_context_v1'||failed==='leave_admin_setup_v1'){await screen.findByLabelText('Alasan policy');fireEvent.click(screen.getByRole('button',{name:'Keanggotaan'}))}
 const retry=failed==='leave_admin_targets_v1'?'Muat ulang anggota':failed==='leave_admin_settings_v1'?'Muat ulang pengaturan':'Muat ulang anggota terpilih';await screen.findByRole('button',{name:retry});await waitFor(()=>expect(client.isFetching()).toBe(0));const stopped=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,40))});expect(mocks.rpc.mock.calls.length).toBe(stopped);expect(stopped).toBeLessThanOrEqual(11)
 failing=false;fireEvent.click(screen.getByRole('button',{name:retry}));if(failed==='leave_admin_targets_v1')await screen.findByRole('button',{name:'Atur Fictional target'});else await screen.findByLabelText(failed==='leave_admin_settings_v1'?'Alasan policy':'Alasan perubahan');await waitFor(()=>expect(client.isFetching()).toBe(0));const recovered=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(recovered);expect(recovered-stopped).toBeLessThanOrEqual(6)
})

test('read-private-only reviews exact target request, frozen charges and paginated private events without actions or calendar scope',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,readPrivate:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional private target',capabilities:{configure:false,adjust:false,readPrivate:true,calendar:false,manageAccess:false}}];const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional private target'}));fireEvent.click(await screen.findByRole('button',{name:'Tinjau pengajuan 2026-10-09 sampai 2026-10-09'}));expect(await screen.findByText('Fictional private reason')).toBeTruthy();expect(await screen.findByText('Fictional event reason')).toBeTruthy();expect(screen.queryByRole('button',{name:'Setujui cuti'})).toBeNull();expect(screen.queryByRole('button',{name:'Simpan penyesuaian'})).toBeNull();expect(screen.queryByRole('button',{name:'Kebijakan dan akses'})).toBeNull();expect(screen.queryByRole('tab',{name:'Kalender'})).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Riwayat peristiwa lebih lama'}));expect(await screen.findByText('Fictional older event')).toBeTruthy();await waitFor(()=>expect(client.isFetching()).toBe(0));const stopped=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,35))});expect(mocks.rpc.mock.calls.length).toBe(stopped);expect(stopped).toBeLessThanOrEqual(12);expect(JSON.stringify(client.getQueryCache().getAll().map(q=>q.queryKey))).not.toContain('Fictional private reason')
})
test('private balance reading and history stay separate from target write context and mutations',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,readPrivate:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional private target',capabilities:{configure:false,adjust:false,readPrivate:true,calendar:false,manageAccess:false}}];mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional private target'}));fireEvent.click(await screen.findByRole('button',{name:'Saldo dan riwayat anggota'}));expect(await screen.findByText('82j 30m')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Buka riwayat saldo anggota'}));expect(await screen.findByText('Penyesuaian jatah')).toBeTruthy();expect(mocks.rpc.mock.calls.some(([name])=>name==='leave_admin_write_context_v1'||name==='leave_transaction_v1')).toBe(false)
})

test('own settings mutation preserves another private draft only after current target grant continuity, and external scope change clears it',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional configured target',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional configured target'}));fireEvent.change(await screen.findByLabelText('Alasan activation'),{target:{value:'Keep another private section'}});fireEvent.change(screen.getByLabelText('Berlaku mulai kebijakan'),{target:{value:'2026-10-03'}});fireEvent.change(screen.getByLabelText('Alasan policy'),{target:{value:'Save explicit future rules'}});fireEvent.click(screen.getByRole('button',{name:'Simpan versi kebijakan'}));await waitFor(()=>expect(finishMutation).toBeDefined());context={...context,scopeVersion:'own-settings-next'};await act(async()=>finishMutation!({data:{id:employeeB,version:2,operation:'save_policy_version'},error:null}));expect(await screen.findByDisplayValue('Keep another private section')).toBeTruthy();expect(guarded()).toBe(true)
 context={...context,scopeVersion:'external-change'};fireEvent(window,new Event('focus'));await waitFor(()=>expect(client.isFetching()).toBe(0));expect((await screen.findByLabelText('Alasan activation') as HTMLTextAreaElement).value).toBe('');expect(guarded()).toBe(false)
})

test.each(['leave_hr_requests_v1','leave_hr_request_v1','leave_hr_request_history_v1','leave_balance_accounts_v1','leave_balance_history_v1'])('private %s failure has bounded requests and fresh retry without cached private display',async failed=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,readPrivate:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional private target',capabilities:{configure:false,adjust:false,readPrivate:true,calendar:false,manageAccess:false}}];let failing=true;const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name===failed&&failing?{abortSignal:()=>Promise.resolve({data:null,error:{code:'55000'}})}:normal(name,args));const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional private target'}))
 if(failed.startsWith('leave_balance')){fireEvent.click(await screen.findByRole('button',{name:'Saldo dan riwayat anggota'}));if(failed==='leave_balance_history_v1')fireEvent.click(await screen.findByRole('button',{name:'Buka riwayat saldo anggota'}))}else if(failed!=='leave_hr_requests_v1')fireEvent.click(await screen.findByRole('button',{name:'Tinjau pengajuan 2026-10-09 sampai 2026-10-09'}))
 const retry=({'leave_hr_requests_v1':'Muat ulang permohonan privat','leave_hr_request_v1':'Muat ulang rincian privat','leave_hr_request_history_v1':'Muat ulang riwayat peristiwa','leave_balance_accounts_v1':'Muat ulang saldo anggota','leave_balance_history_v1':'Muat ulang riwayat saldo anggota'} as Record<string,string>)[failed]
 await screen.findByRole('button',{name:retry});await waitFor(()=>expect(client.isFetching()).toBe(0));const stopped=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,35))});expect(mocks.rpc.mock.calls.length).toBe(stopped);expect(stopped).toBeLessThanOrEqual(13)
 failing=false;fireEvent.click(screen.getByRole('button',{name:retry}));const expected=failed==='leave_hr_requests_v1'?'Buka rincian privat':failed==='leave_hr_request_v1'?'Fictional private reason':failed==='leave_hr_request_history_v1'?'Fictional event reason':failed==='leave_balance_accounts_v1'?'82j 30m':'Penyesuaian jatah';await screen.findByText(expected);await waitFor(()=>expect(client.isFetching()).toBe(0));const recovered=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,30))});expect(mocks.rpc.mock.calls.length).toBe(recovered);expect(recovered-stopped).toBeLessThanOrEqual(4)
})
test('canceled private HR authority hides reasons and events until genuine recovery, and actor/scope changes cannot restore old target data',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,readPrivate:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional private target',capabilities:{configure:false,adjust:false,readPrivate:true,calendar:false,manageAccess:false}}];const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional private target'}));fireEvent.click(await screen.findByRole('button',{name:'Tinjau pengajuan 2026-10-09 sampai 2026-10-09'}));await screen.findByText('Fictional event reason');pausedContext=true;fireEvent(window,new Event('focus'));await waitFor(()=>expect(pendingSignals.length).toBeGreaterThan(0));await act(async()=>client.cancelQueries({queryKey:leaveKeys.context(hrA,'current'),exact:true}));expect(screen.queryByText('Fictional private reason')).toBeNull();expect(screen.queryByText('Fictional event reason')).toBeNull();const stopped=mocks.rpc.mock.calls.length;await act(async()=>{await new Promise(r=>setTimeout(r,35))});expect(mocks.rpc.mock.calls.length).toBe(stopped)
 pausedContext=false;fireEvent.click(within(screen.getByText('Akses cuti belum dapat dikonfirmasi. Silakan coba lagi.').closest('[role=alert]') as HTMLElement).getByRole('button',{name:'Coba lagi'}));await screen.findByText('Fictional event reason');context={...context,scopeVersion:'revoked-private',capabilities:none};targets=[];fireEvent(window,new Event('focus'));await waitFor(()=>expect(screen.queryByRole('tab',{name:'Pengaturan'})).toBeNull());expect(screen.queryByText('Fictional private reason')).toBeNull();expect(screen.queryByText('Fictional event reason')).toBeNull();expect(client.getQueryCache().getAll().some(query=>query.queryKey[3]==='private'&&query.queryKey[4]===scope)).toBe(false)
})

test('sign-out keeps a dirty private owner until the user confirms discarding it',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional configured target',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional configured target'}));fireEvent.change(await screen.findByLabelText('Alasan policy'),{target:{value:'Keep before sign-out'}});fireEvent.click(screen.getByRole('button',{name:'Menu pengguna'}));fireEvent.click(screen.getByRole('button',{name:'Keluar'}));expect(mocks.auth.signOut).not.toHaveBeenCalled();expect(screen.getByDisplayValue('Keep before sign-out')).toBeTruthy();expect(window.confirm).toHaveBeenCalled()
})
test('uncertain admin submission preserves only command metadata and requires recovery before another send',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional configured target',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional configured target'}));fireEvent.change(await screen.findByLabelText('Berlaku mulai kebijakan'),{target:{value:'2026-10-03'}});fireEvent.change(screen.getByLabelText('Alasan policy'),{target:{value:'Ephemeral admin reason'}});fireEvent.click(screen.getByRole('button',{name:'Simpan versi kebijakan'}));await waitFor(()=>expect(finishMutation).toBeDefined());await act(async()=>finishMutation!({data:null,error:{code:'FETCH_ERROR',message:'private network details'}}));await screen.findByRole('button',{name:'Pulihkan hasil pengaturan'});expect(screen.queryByText('private network details')).toBeNull();expect(screen.queryByRole('button',{name:'Simpan versi kebijakan'})).toBeNull();expect(localStorage.length).toBe(1);const saved=JSON.parse(localStorage.getItem(localStorage.key(0)!)!);expect(Object.keys(saved).sort()).toEqual(['id','key','uncertain']);expect(JSON.stringify(saved)).not.toContain('Ephemeral admin reason')
 const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name==='leave_reconcile_request_v1'?Promise.resolve({data:{state:'committed',result:{id:employeeB,version:2,operation:'save_policy_version'}},error:null}):normal(name,args));fireEvent.click(screen.getByRole('button',{name:'Pulihkan hasil pengaturan'}));await screen.findByLabelText('Alasan policy');expect(localStorage.length).toBe(0);expect(mocks.rpc.mock.calls.filter(([name])=>name==='leave_transaction_v1')).toHaveLength(1)
})

test('interrupted calendar data read has an explicit retry while shared authority remains valid',async()=>{
 const {client}=mount();fireEvent.click(await screen.findByRole('tab',{name:'Kalender'}));await screen.findByText('Fictional calendar employee');const normal=mocks.rpc.getMockImplementation()!;let signal:AbortSignal|undefined;mocks.rpc.mockImplementation((name,args)=>name==='leave_calendar_v1'?{abortSignal:(value:AbortSignal)=>{signal=value;return new Promise(()=>{})}}:normal(name,args));fireEvent(window,new Event('focus'));await waitFor(()=>expect(signal).toBeDefined());await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[5]==='team-calendar'}));expect(screen.queryByText('Fictional calendar employee')).toBeNull();mocks.rpc.mockImplementation(normal);fireEvent.click(await screen.findByRole('button',{name:'Muat ulang kalender'}));expect(await screen.findByText('Fictional calendar employee')).toBeTruthy()
})
test('failed target directory refresh hides an open private editor and provides an explicit retry',async()=>{
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,configure:true},balances:[],currentPeriod:null};audiences=[];targets=[{id:employeeA,name:'Fictional configured target',capabilities:{configure:true,adjust:false,readPrivate:false,calendar:false,manageAccess:false}}];mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional configured target'}));fireEvent.change(await screen.findByLabelText('Alasan policy'),{target:{value:'Directory interrupted draft'}});const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_targets_v1'?{abortSignal:()=>Promise.resolve({data:null,error:{code:'55000'}})}:normal(name,args));fireEvent(window,new Event('focus'));expect(await screen.findByRole('button',{name:'Muat ulang akses anggota'})).toBeTruthy();expect(screen.queryByDisplayValue('Directory interrupted draft')).toBeNull();expect(guarded()).toBe(true);mocks.rpc.mockImplementation(normal);fireEvent.click(screen.getByRole('button',{name:'Muat ulang akses anggota'}));expect(await screen.findByDisplayValue('Directory interrupted draft')).toBeTruthy()
})

async function settledBudget(client:QueryClient,max:number){
 await waitFor(()=>expect(client.isFetching()).toBe(0));const calls=mocks.rpc.mock.calls.length
 await act(async()=>{await new Promise(resolve=>setTimeout(resolve,35))});expect(mocks.rpc.mock.calls.length).toBe(calls);expect(calls).toBeLessThanOrEqual(max);return calls
}
function adminActor(capability:'configure'|'adjust'|'readPrivate'|'manageAccess'='configure'){
 identity(hrA);context={...personal,memberKind:null,capabilities:{...none,[capability]:true},balances:[],currentPeriod:null};audiences=[]
 targets=[{id:employeeA,name:'Fictional target',capabilities:{configure:false,adjust:false,readPrivate:false,calendar:false,manageAccess:false,[capability]:true}}]
}
const groupId='85000000-0000-0000-0000-000000000001'
const calendarFixture={id:employeeB,name:'Fictional rota',version:1,effectiveFrom:'2026-10-01',effectiveUntil:null,timezone:'Etc/UTC',confirmedTimezone:'Etc/UTC',holidaysConfirmed:false,sundayMinutes:null,holidays:[],groups:[{id:groupId,name:'Fictional group',onAnchor:true}],impacts:{available:false,pendingCount:null,approvedCount:null}}
function setupOptions(){
 const normal=mocks.rpc.getMockImplementation()!
 mocks.rpc.mockImplementation((name,args)=>{
  if(name==='leave_admin_write_context_v1')return {abortSignal:()=>Promise.resolve({data:{...response(name,args),memberOptions:{state:'available',calendars:[{id:employeeB,name:'Fictional current lineage'}],groups:[{id:groupId,name:'Fictional group'}]}},error:null})}
  if(name==='leave_admin_setup_v1'&&['approvers','rota'].includes(args.p_section))return {abortSignal:()=>Promise.resolve({data:{rows:args.p_section==='rota'?[calendarFixture]:[{id:managerA,name:'Fictional approver',memberKind:'manager',active:true}],total:1,page:args.p_page,pageSize:args.p_page_size},error:null})}
  if(name==='leave_admin_rota_context_v1')return {abortSignal:()=>Promise.resolve({data:{calendarId:employeeB,scopeVersion:context.scopeVersion,authorityKey:'a'.repeat(64),calendar:calendarFixture},error:null})}
  if(name==='leave_calendar_preview_v1')return {abortSignal:()=>Promise.resolve({data:{calendarId:employeeB,calendarVersion:1,fingerprint:'calendar-fingerprint',impacts:{available:true,pendingCount:0,approvedCount:0}},error:null})}
  if(name==='leave_roster_preview_v1')return {abortSignal:()=>Promise.resolve({data:{calendarId:employeeB,calendarVersion:2,fingerprint:'server-fingerprint',rows:[{date:'2026-10-10',groupId,capacityMinutes:225}],impacts:{available:true,pendingCount:0,approvedCount:0}},error:null})}
  return normal(name,args)
 })
}
async function memberEditor(){fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target'}));await screen.findByLabelText('Alasan policy');fireEvent.click(screen.getByRole('button',{name:'Keanggotaan'}));await screen.findByLabelText('Berlaku mulai')}
async function rotaEditor(){fireEvent.click(await screen.findByRole('button',{name:'Kalender dan roster perusahaan'}));fireEvent.click(await screen.findByRole('button',{name:'Atur kalender Fictional rota'}));await screen.findByLabelText('Nama kalender')}
function change(label:string,value:string){fireEvent.change(screen.getByLabelText(label),{target:{value}})}
test.each(['configure','adjust','readPrivate','manageAccess'] as const)('independent calendar discovery survives combined %s capability and revocation, without inferring an audience',async capability=>{
 adminActor(capability);audiences=['granted'];const {client}=mount();await screen.findByRole('tab',{name:'Kalender'});expect(tab('Pengaturan').getAttribute('aria-selected')).toBe('true');await settledBudget(client,4)
 fireEvent.click(tab('Kalender'));await screen.findByText('Fictional calendar employee');await settledBudget(client,8)
 audiences=[];context={...context,scopeVersion:'calendar-revoked'};fireEvent(window,new Event('focus'));await screen.findByRole('tab',{name:'Pengaturan'});await settledBudget(client,16)
 expect(screen.queryByRole('tab',{name:'Kalender'})).toBeNull();expect(screen.queryByText('Fictional calendar employee')).toBeNull()
})
test('data-only policy cancellation retains a guarded draft and exposes a fresh-read retry',async()=>{
 adminActor();const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target'}));await screen.findByLabelText('Alasan policy');change('Alasan policy','Private retained policy');const normal=mocks.rpc.getMockImplementation()!;let started=false
 mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_settings_v1'?{abortSignal:()=>{started=true;return new Promise(()=>{})}}:normal(name,args));fireEvent(window,new Event('focus'));await waitFor(()=>expect(started).toBe(true));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[6]==='target'}))
 await settledBudget(client,11);expect(screen.queryByDisplayValue('Private retained policy')).toBeNull();expect(guarded()).toBe(true);mocks.rpc.mockImplementation(normal);fireEvent.click(await screen.findByRole('button',{name:'Muat ulang pengaturan'}));await screen.findByDisplayValue('Private retained policy');expect(guarded()).toBe(true);await settledBudget(client,13)
})
test('canceled policy continuity read after an own mutation waits for explicit fresh proof without losing another section',async()=>{
 adminActor();const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target'}));await screen.findByLabelText('Alasan policy');change('Alasan activation','Keep activation draft');change('Alasan policy','Save policy');change('Berlaku mulai kebijakan','2026-10-03');fireEvent.click(screen.getByRole('button',{name:'Simpan versi kebijakan'}));await waitFor(()=>expect(finishMutation).toBeDefined())
 const normal=mocks.rpc.getMockImplementation()!;let started=false;mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_settings_v1'?{abortSignal:()=>{started=true;return new Promise(()=>{})}}:normal(name,args));context={...context,scopeVersion:'own-policy-canceled'};await act(async()=>finishMutation!({data:{id:employeeB,version:2,operation:'save_policy_version'},error:null}));await waitFor(()=>expect(started).toBe(true));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[6]==='target'}));await settledBudget(client,15)
 expect(screen.queryByDisplayValue('Keep activation draft')).toBeNull();expect(guarded()).toBe(true);mocks.rpc.mockImplementation(normal);fireEvent.click(await screen.findByRole('button',{name:'Muat ulang pengaturan'}));await screen.findByDisplayValue('Keep activation draft');expect(guarded()).toBe(true);await settledBudget(client,17)
})
test.each([
 ['leave_hr_requests_v1','hr-requests','Muat ulang permohonan privat','Buka rincian privat'],
 ['leave_hr_request_v1','hr-request','Muat ulang rincian privat','Fictional private reason'],
 ['leave_hr_request_history_v1','hr-history','Muat ulang riwayat peristiwa','Fictional event reason'],
 ['leave_balance_accounts_v1','private-balances','Muat ulang saldo anggota','82j 30m'],
 ['leave_balance_history_v1','private-balance-history','Muat ulang riwayat saldo anggota','Penyesuaian jatah'],
])('canceled %s data has an idle retry and bounded fresh recovery',async(rpc,family,retry,visible)=>{
 adminActor('readPrivate');const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target'}))
 if(rpc.startsWith('leave_balance')){fireEvent.click(await screen.findByRole('button',{name:'Saldo dan riwayat anggota'}));await screen.findByText('82j 30m');if(rpc==='leave_balance_history_v1')fireEvent.click(screen.getByRole('button',{name:'Buka riwayat saldo anggota'}))}else if(rpc!=='leave_hr_requests_v1')fireEvent.click(await screen.findByRole('button',{name:'Tinjau pengajuan 2026-10-09 sampai 2026-10-09'}))
 await screen.findByText(visible);await settledBudget(client,14);const normal=mocks.rpc.getMockImplementation()!;let started=false;mocks.rpc.mockImplementation((name,args)=>name===rpc?{abortSignal:()=>{started=true;return new Promise(()=>{})}}:normal(name,args));fireEvent(window,new Event('focus'));await waitFor(()=>expect(started).toBe(true));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[6]===family}));const stopped=await settledBudget(client,21);expect(screen.queryByText(visible)).toBeNull()
 mocks.rpc.mockImplementation(normal);fireEvent.click(await screen.findByRole('button',{name:retry}));await screen.findByText(visible);expect(await settledBudget(client,25)-stopped).toBeLessThanOrEqual(4)
})
const memberFields={member:['Mulai bekerja','2020-02-02','Simpan anggota','set_member'],approver:['Penyetuju',managerA,'Simpan penyetuju','set_approver'],group:['Kelompok Sabtu',groupId,'Simpan kelompok','set_group_membership']}
test.each([['member','approver'],['member','group'],['approver','member'],['approver','group'],['group','member'],['group','approver']] as const)('own %s save retains unsent %s section through a real scope change, but external scope clears it',async(saved,retained)=>{
 adminActor();setupOptions();const {client}=mount();await memberEditor();change(memberFields[saved][0],memberFields[saved][1]);change(memberFields[retained][0],memberFields[retained][1]);change('Berlaku mulai','2026-10-20');change('Alasan perubahan','Save only one section');fireEvent.click(screen.getByRole('button',{name:memberFields[saved][2]}));await waitFor(()=>expect(finishMutation).toBeDefined());const payload=mocks.rpc.mock.calls.find(([name])=>name==='leave_transaction_v1')![1].p_payload
 if(saved==='member')expect(payload).not.toHaveProperty('approver_id');else expect(payload).not.toHaveProperty('employment_start')
 context={...context,scopeVersion:'own-member-next'};await act(async()=>finishMutation!({data:{id:employeeA,version:2,operation:memberFields[saved][3]},error:null}));await screen.findByText('Pengaturan tersimpan. Muat ulang konteks sebelum tindakan berikutnya.');expect((screen.getByLabelText(memberFields[retained][0]) as HTMLInputElement).value).toBe(memberFields[retained][1]);expect(guarded()).toBe(true);await settledBudget(client,22)
 context={...context,scopeVersion:'external-member-change'};fireEvent(window,new Event('focus'));await waitFor(()=>expect((screen.getByLabelText('Penyetuju') as HTMLSelectElement).value).toBe(''));await settledBudget(client,32);expect(guarded()).toBe(false);expect((screen.getByLabelText('Berlaku mulai') as HTMLInputElement).value).toBe('')
})
test('own member save preserves standalone dates but discards drafts if completed target grant identity changes',async()=>{
 adminActor();setupOptions();const {client}=mount();await memberEditor();change('Berlaku mulai','2026-10-20');change('Alasan perubahan','Save member');fireEvent.click(screen.getByRole('button',{name:'Simpan anggota'}));await waitFor(()=>expect(finishMutation).toBeDefined());context={...context,scopeVersion:'own-member-next'};await act(async()=>finishMutation!({data:{id:employeeA,version:2,operation:'set_member'},error:null}));await screen.findByText('Pengaturan tersimpan. Muat ulang konteks sebelum tindakan berikutnya.');expect((screen.getByLabelText('Berlaku mulai') as HTMLInputElement).value).toBe('2026-10-20');expect(guarded()).toBe(true)
 finishMutation=undefined;fireEvent.click(screen.getByRole('button',{name:'Simpan anggota'}));await waitFor(()=>expect(finishMutation).toBeDefined());const normal=mocks.rpc.getMockImplementation()!;mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_write_context_v1'?{abortSignal:()=>Promise.resolve({data:{...response(name,args),authorityKey:'b'.repeat(64)},error:null})}:normal(name,args));context={...context,scopeVersion:'different-grant'};await act(async()=>finishMutation!({data:{id:employeeA,version:3,operation:'set_member'},error:null}));await waitFor(()=>expect((screen.getByLabelText('Berlaku mulai') as HTMLInputElement).value).toBe(''));expect(guarded()).toBe(false);await settledBudget(client,32)
})
test.each(['rota','rota-context'])('canceled %s data exposes explicit retry while hiding retained private controls',async family=>{
 adminActor();setupOptions();const {client}=mount();if(family==='rota-context'){await rotaEditor();change('Alasan perubahan','Hidden rota draft')}else{fireEvent.click(await screen.findByRole('button',{name:'Kalender dan roster perusahaan'}));await screen.findByRole('button',{name:'Atur kalender Fictional rota'})}
 const normal=mocks.rpc.getMockImplementation()!;let started=false;mocks.rpc.mockImplementation((name,args)=>(family==='rota'?name==='leave_admin_setup_v1'&&args.p_section==='rota':name==='leave_admin_rota_context_v1')?{abortSignal:()=>{started=true;return new Promise(()=>{})}}:normal(name,args));fireEvent(window,new Event('focus'));await waitFor(()=>expect(started).toBe(true));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[6]===family}));await settledBudget(client,15)
 if(family==='rota-context'){expect(screen.queryByDisplayValue('Hidden rota draft')).toBeNull();expect(guarded()).toBe(true)}
 mocks.rpc.mockImplementation(normal);fireEvent.click(await screen.findByRole('button',{name:family==='rota'?'Muat ulang kalender perusahaan':'Muat ulang kalender terpilih'}));if(family==='rota-context')await screen.findByDisplayValue('Hidden rota draft');else await screen.findByRole('button',{name:'Atur kalender Fictional rota'});await settledBudget(client,17)
})
test('calendar own-save scope refresh keeps an unpublished roster until publication, and external scope erases a later draft',async()=>{
 adminActor();setupOptions();const {client}=mount();await rotaEditor();change('Nama kalender','Edited calendar');change('Sabtu acuan','2026-10-10');change('Publikasi mulai','2026-10-10');change('Publikasi sampai (eksklusif)','2026-10-31');change('Alasan perubahan','Save calendar only');fireEvent.click(screen.getByRole('button',{name:'Pratinjau dampak kalender'}));await waitFor(()=>expect((screen.getByRole('button',{name:'Simpan versi kalender'}) as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Simpan versi kalender'}));await waitFor(()=>expect(finishMutation).toBeDefined());context={...context,scopeVersion:'own-calendar-next'};await act(async()=>finishMutation!({data:{id:employeeB,version:2,operation:'save_calendar_version'},error:null}));await screen.findByText('Pengaturan tersimpan.');expect((screen.getByLabelText('Sabtu acuan') as HTMLInputElement).value).toBe('2026-10-10');expect(guarded()).toBe(true);await settledBudget(client,18)
 fireEvent.click(screen.getByRole('button',{name:'Pratinjau roster'}));await screen.findByText('2026-10-10 · Fictional group · 225 menit');finishMutation=undefined;fireEvent.click(screen.getByRole('button',{name:'Terbitkan roster'}));await waitFor(()=>expect(finishMutation).toBeDefined());context={...context,scopeVersion:'own-roster-next'};await act(async()=>finishMutation!({data:{id:employeeB,version:3,operation:'publish_roster'},error:null}));await waitFor(()=>expect(guarded()).toBe(false));await settledBudget(client,28)
 change('Alasan perubahan','External change must erase');context={...context,scopeVersion:'external-rota-change'};fireEvent(window,new Event('focus'));await waitFor(()=>expect((screen.getByLabelText('Alasan perubahan') as HTMLInputElement).value).toBe(''));expect(guarded()).toBe(false);await settledBudget(client,37)
})

test('own member readback cancellation preserves dates off-screen until a current same-grant retry completes',async()=>{
 adminActor();setupOptions();const {client}=mount();await memberEditor();change('Berlaku mulai','2026-10-20');change('Alasan perubahan','Save member only');fireEvent.click(screen.getByRole('button',{name:'Simpan anggota'}));await waitFor(()=>expect(finishMutation).toBeDefined())
 const normal=mocks.rpc.getMockImplementation()!;let started=false;mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_write_context_v1'?{abortSignal:()=>{started=true;return new Promise(()=>{})}}:normal(name,args));context={...context,scopeVersion:'own-member-readback-canceled'};await act(async()=>finishMutation!({data:{id:employeeA,version:2,operation:'set_member'},error:null}));await waitFor(()=>expect(started).toBe(true));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[6]==='member-write'}));await settledBudget(client,20);expect(screen.queryByDisplayValue('2026-10-20')).toBeNull();expect(guarded()).toBe(true)
 mocks.rpc.mockImplementation(normal);fireEvent.click(await screen.findByRole('button',{name:'Muat ulang anggota terpilih'}));await screen.findByDisplayValue('2026-10-20');expect(guarded()).toBe(true);expect(mocks.rpc.mock.calls.filter(([name])=>name==='leave_transaction_v1')).toHaveLength(1);await settledBudget(client,24)
})
test.each(['scope','permission','actor'] as const)('member drafts cannot survive an external %s change while a command is awaiting its receipt',async kind=>{
 adminActor();setupOptions();const {client,view,element}=mount();await memberEditor();change('Berlaku mulai','2026-10-20');change('Alasan perubahan','Pending member draft');fireEvent.click(screen.getByRole('button',{name:'Simpan anggota'}));await waitFor(()=>expect(finishMutation).toBeDefined())
 if(kind==='actor'){identity(employeeB);context=personal;await act(async()=>mocks.listeners.forEach(update=>update()));view.rerender(element())}else{context={...context,scopeVersion:'external-before-receipt',...(kind==='permission'?{capabilities:none}: {})};if(kind==='permission')targets=[];fireEvent(window,new Event('focus'))}
 await waitFor(()=>expect(screen.queryByDisplayValue('Pending member draft')).toBeNull());await waitFor(()=>expect(guarded()).toBe(kind==='scope'));await act(async()=>finishMutation!({data:{id:employeeA,version:2,operation:'set_member'},error:null}));await settledBudget(client,25);expect(screen.queryByDisplayValue('2026-10-20')).toBeNull();expect(guarded()).toBe(false)
})

test('calendar discovery retry adds an independent grant without replacing a dirty settings owner',async()=>{
 adminActor();const {client}=mount();fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target'}));await screen.findByLabelText('Alasan policy');change('Alasan policy','Keep combined grant draft')
 const normal=mocks.rpc.getMockImplementation()!;let started=false;mocks.rpc.mockImplementation((name,args)=>name==='leave_reads_context_v1'?{abortSignal:()=>{started=true;return new Promise(()=>{})}}:normal(name,args));fireEvent(window,new Event('focus'));await waitFor(()=>expect(started).toBe(true));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[5]==='read-access'}));await settledBudget(client,11)
 mocks.rpc.mockImplementation(normal);audiences=['granted'];fireEvent.click(await screen.findByRole('button',{name:'Muat ulang pilihan kalender'}));await screen.findByRole('tab',{name:'Kalender'});await screen.findByDisplayValue('Keep combined grant draft');expect(tab('Pengaturan').getAttribute('aria-selected')).toBe('true');expect(guarded()).toBe(true);await settledBudget(client,13)
})

test.each(['same-grant','changed-grant','denied-grant','second-scope'] as const)('rota own-save readback cancellation recovers only with %s proof',async result=>{
 adminActor();setupOptions();const {client}=mount();await rotaEditor();change('Sabtu acuan','2026-10-10');change('Alasan perubahan','Save calendar only');fireEvent.click(screen.getByRole('button',{name:'Pratinjau dampak kalender'}));await waitFor(()=>expect((screen.getByRole('button',{name:'Simpan versi kalender'}) as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Simpan versi kalender'}));await waitFor(()=>expect(finishMutation).toBeDefined())
 const normal=mocks.rpc.getMockImplementation()!;let started=false;mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_rota_context_v1'?{abortSignal:()=>{started=true;return new Promise(()=>{})}}:normal(name,args));context={...context,scopeVersion:'own-rota-awaiting-proof'};await act(async()=>finishMutation!({data:{id:employeeB,version:2,operation:'save_calendar_version'},error:null}));await waitFor(()=>expect(started).toBe(true));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[6]==='rota-context'}));await settledBudget(client,19);expect(screen.queryByDisplayValue('2026-10-10')).toBeNull();expect(guarded()).toBe(true)
 if(result==='second-scope'){context={...context,scopeVersion:'external-while-waiting'};fireEvent(window,new Event('focus'));await waitFor(()=>expect(guarded()).toBe(false));await act(async()=>client.cancelQueries({predicate:q=>q.queryKey[6]==='rota-context'}))}
 mocks.rpc.mockImplementation((name,args)=>name==='leave_admin_rota_context_v1'&&result==='denied-grant'?{abortSignal:()=>Promise.resolve({data:null,error:{code:'42501'}})}:name==='leave_admin_rota_context_v1'&&result==='changed-grant'?{abortSignal:()=>Promise.resolve({data:{calendarId:employeeB,scopeVersion:context.scopeVersion,authorityKey:'b'.repeat(64),calendar:calendarFixture},error:null})}:normal(name,args));fireEvent.click(await screen.findByRole('button',{name:'Muat ulang kalender terpilih'}));await settledBudget(client,29)
 if(result==='same-grant'){await screen.findByDisplayValue('2026-10-10');expect(guarded()).toBe(true)}else{expect(screen.queryByDisplayValue('2026-10-10')).toBeNull();expect(guarded()).toBe(false)}
 expect(mocks.rpc.mock.calls.filter(([name])=>name==='leave_transaction_v1')).toHaveLength(1)
})

test.each(['policy','member'] as const)('explicit target denial clears %s drafts while ordinary failures retain retryable private state',async panel=>{
 adminActor();setupOptions();const {client}=mount();if(panel==='member')await memberEditor();else{fireEvent.click(await screen.findByRole('button',{name:'Atur Fictional target'}));await screen.findByLabelText('Alasan policy')}
 const label=panel==='member'?'Alasan perubahan':'Alasan policy';change(label,'Private target draft');const normal=mocks.rpc.getMockImplementation()!;let code='55000';const rpc=panel==='member'?'leave_admin_write_context_v1':'leave_admin_settings_v1';mocks.rpc.mockImplementation((name,args)=>name===rpc?{abortSignal:()=>Promise.resolve({data:null,error:{code,message:'Private diagnostic'}})}:normal(name,args));fireEvent(window,new Event('focus'));await settledBudget(client,17);expect(screen.queryByDisplayValue('Private target draft')).toBeNull();expect(guarded()).toBe(true)
 code='42501';fireEvent.click(await screen.findByRole('button',{name:panel==='member'?'Muat ulang anggota terpilih':'Muat ulang pengaturan'}));await settledBudget(client,21);expect(guarded()).toBe(false);expect(screen.queryByText('Private diagnostic')).toBeNull()
 mocks.rpc.mockImplementation(normal);fireEvent.click(screen.getByRole('button',{name:panel==='member'?'Muat ulang anggota terpilih':'Muat ulang pengaturan'}));expect((await screen.findByLabelText(label) as HTMLInputElement).value).toBe('');await settledBudget(client,25)
})
