-- FICTIONAL OWNER SETUP ONLY. Input is generated by capacity-sql.mjs in the same transaction.
-- Never installs policy or approval choices for real people. All product triggers remain enabled.
CREATE FUNCTION pg_temp.capacity_id(k text,v text) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$
 SELECT (substr(h,1,8)||'-'||substr(h,9,4)||'-4'||substr(h,14,3)||'-a'||substr(h,18,3)||'-'||substr(h,21,12))::uuid
 FROM (SELECT encode(sha256(convert_to('ihr-capacity-v1-20261003:'||k||':'||v,'UTF8')),'hex') h) x
$$;
CREATE SCHEMA ihr_capacity_fixture;
REVOKE ALL ON SCHEMA ihr_capacity_fixture FROM PUBLIC,anon,authenticated;
CREATE TABLE ihr_capacity_fixture.identity(seed text PRIMARY KEY,as_of date NOT NULL,input_hash text NOT NULL,uuid_hash text NOT NULL);
INSERT INTO ihr_capacity_fixture.identity SELECT j->>'seed',(j->>'asOf')::date,input_hash,uuid_hash FROM capacity_input;
-- Each state transition is owner-derived setup, never asserted to prove an application permission.
DO $fixture$
DECLARE f jsonb;v jsonb;d jsonb;step text;employee uuid;approver uuid;account uuid;request uuid;policy uuid:=pg_temp.capacity_id('policy','1');
 calendar uuid:=pg_temp.capacity_id('calendar','1');calendar_version uuid:=pg_temp.capacity_id('calendar-version','1');
 owner_id uuid:=pg_temp.capacity_id('person','479');epoch timestamptz:='2023-01-01 00:00:00+00';
 grantor uuid;approval uuid;kind text;q jsonb;at_time timestamptz;event_actor uuid;next_status text;event_name text;ledger_kind text;
 attempt uuid;original_ledger uuid;reversal_ledger uuid;reserved integer;used integer;a public.ihr_leave_accounts%ROWTYPE;step_index integer;attempt_number integer;event_reason text;event_key text;
BEGIN
 SELECT j INTO STRICT f FROM capacity_input;
 IF current_user<>'postgres' OR auth.uid() IS NOT NULL OR EXISTS(SELECT 1 FROM public.ihr_leave_members) THEN
  RAISE EXCEPTION 'Capacity materialization requires owner, cleared JWT and a fresh empty iHR schema'; END IF;
 INSERT INTO auth.users(id) SELECT (p->>'id')::uuid FROM jsonb_array_elements(f->'people') p;
 INSERT INTO public.users(id,full_name,email,role,is_active)
 SELECT (p->>'id')::uuid,p->>'name','fictional-capacity-'||(p->>'n')||'@example.invalid','sales_person'::public.user_role,true FROM jsonb_array_elements(f->'people') p;
 INSERT INTO private.ihr_leave_calendar_registry VALUES(calendar,1);
 INSERT INTO public.ihr_leave_calendars(id,calendar_id,version,name,effective_from,effective_until,timezone,holidays_confirmed,sunday_minutes,created_by,created_at)
 VALUES(calendar_version,calendar,1,'Fictional Capacity Calendar','2024-01-01','2027-10-05','Etc/UTC',true,0,owner_id,epoch);
 INSERT INTO public.ihr_leave_policies(id,version,effective_from,effective_until,annual_policy_confirmed,created_by,created_at,
 minimum_notice_days,booking_horizon_days,reason_required,request_rules_confirmed,reserve_pending_accepted,single_date_rule_accepted,
 cancellation_rules_confirmed,cancellation_mode,cancellation_allow_past,cancellation_allow_repeat_declined,cancellation_reason_required,calendar_audience,calendar_audience_confirmed)
 VALUES(policy,1,'2024-01-01','2027-10-05',true,owner_id,epoch,0,366,true,true,true,true,true,'whole_request',true,true,true,'explicit_grants',true);
 INSERT INTO public.ihr_leave_members(user_id,member_kind,active,employment_start,eligibility_date,cycle_state,timezone,active_policy_id,active_calendar_id,
 annual_policy_confirmed,opening_reconciled,reserve_pending_accepted,single_date_rule_accepted,created_at,updated_at)
 SELECT (p->>'id')::uuid,p->>'kind',true,CASE WHEN p->>'kind'<>'director' THEN '2020-01-01'::date END,
 CASE WHEN p->>'kind'<>'director' THEN '2021-01-01'::date END,CASE WHEN p->>'kind'='director' THEN 'first_grant_blocked' ELSE 'established_calendar' END,
 CASE WHEN p->>'kind'<>'director' THEN 'Etc/UTC' END,CASE WHEN p->>'kind'<>'director' THEN policy END,CASE WHEN p->>'kind'<>'director' THEN calendar END,
 p->>'kind'<>'director',p->>'kind'<>'director',p->>'kind'<>'director',p->>'kind'<>'director',epoch,epoch FROM jsonb_array_elements(f->'people') p;
 FOR v IN SELECT value FROM jsonb_array_elements(f->'people') WHERE value->>'kind'<>'director' LOOP
  employee:=(v->>'id')::uuid;
  approver:=pg_temp.capacity_id('person',CASE WHEN (v->>'n')::int>500 THEN '481' WHEN (v->>'n')::int<=240 THEN '481' WHEN (v->>'n')::int<=244 THEN '482'
   WHEN (v->>'n')::int<=480 THEN (483+(((v->>'n')::int-245)%13))::text ELSE (496+(((v->>'n')::int-481)%5))::text END);
  INSERT INTO public.ihr_leave_approvers(id,employee_id,approver_id,effective_from,effective_until,assigned_by,created_at,updated_at)
  VALUES(pg_temp.capacity_id('assignment',v->>'n'),employee,approver,'2024-01-01','2027-10-05',owner_id,epoch,epoch);
 END LOOP;
 INSERT INTO public.ihr_saturday_groups(id,calendar_id,name) VALUES(pg_temp.capacity_id('group','A'),calendar,'Fictional A'),(pg_temp.capacity_id('group','B'),calendar,'Fictional B');
 INSERT INTO public.ihr_saturday_memberships(id,employee_id,group_id,effective_from,effective_until,created_by,created_at)
 SELECT (m->>'id')::uuid,pg_temp.capacity_id('person',m->>'employee'),pg_temp.capacity_id('group',m->>'group'),(m->>'from')::date,(m->>'until')::date,owner_id,epoch FROM jsonb_array_elements(f->'memberships') m;
 INSERT INTO public.ihr_saturday_roster(id,calendar_version_id,group_id,version,day,capacity_minutes,anchor,on_anchor,effective_from,effective_until,published_by,published_at)
 SELECT (r->>'id')::uuid,calendar_version,pg_temp.capacity_id('group',r->>'group'),1,(r->>'date')::date,(r->>'minutes')::int,'2024-01-06',r->>'group'='A','2024-01-01','2027-10-05',owner_id,epoch FROM jsonb_array_elements(f->'roster') r;
 INSERT INTO public.ihr_leave_calendar_exceptions(id,calendar_version_id,day,kind)
 SELECT pg_temp.capacity_id('holiday',h),calendar_version,h::date,'holiday' FROM jsonb_array_elements_text(f->'holidays') h;
 FOR v IN SELECT value FROM jsonb_array_elements(f->'grants') LOOP
  grantor:=owner_id;
  INSERT INTO public.ihr_leave_access_grants(id,actor_id,capability,scope_kind,employee_id,effective_from,effective_until,granted_by,reason,created_at,updated_at)
  VALUES((v->>'id')::uuid,pg_temp.capacity_id('person',v->>'actor'),v->>'capability','employee',pg_temp.capacity_id('person',v->>'employee'),'2024-01-01','2027-10-05',grantor,'FICTIONAL capacity permission only',epoch,epoch);
  INSERT INTO private.ihr_leave_access_manifests(id,grant_id,actor_id,grantor_id,capability,scope_kind,employee_id,effective_from,effective_until,approved_by,approved_at,approval_reference,confirmed)
  VALUES(pg_temp.capacity_id('manifest',v->>'id'),(v->>'id')::uuid,pg_temp.capacity_id('person',v->>'actor'),grantor,v->>'capability','employee',pg_temp.capacity_id('person',v->>'employee'),'2024-01-01','2027-10-05',pg_temp.capacity_id('person','478'),epoch,'FICTIONAL externally provisioned synthetic fixture only',true);
 END LOOP;
 FOR v IN SELECT value FROM jsonb_array_elements(f->'people') WHERE value->>'kind'<>'director' LOOP
  employee:=(v->>'id')::uuid;
  FOREACH kind IN ARRAY ARRAY['retention','access_review'] LOOP
   approval:=pg_temp.capacity_id('governance',(v->>'n')||':'||kind);
   INSERT INTO private.ihr_leave_governance_approvals(id,employee_id,kind,rule_id,rule_version,rule_document,approved_by,approved_at,accountable_owner,cadence,capabilities,grant_ids,audience_ids,confirmed)
   VALUES(approval,employee,kind,pg_temp.capacity_id('rule',kind),1,jsonb_build_object('fictional',true,'rule',kind),pg_temp.capacity_id('person','478'),epoch,owner_id,
    CASE WHEN kind='access_review' THEN 'Fictional annual test review' END,ARRAY['configure','adjust','read_private','calendar','manage_access'],ARRAY(SELECT id FROM public.ihr_leave_access_grants WHERE employee_id=employee),ARRAY[employee],true);
   INSERT INTO private.ihr_leave_governance_references VALUES(employee,kind,1,approval,owner_id,epoch);
  END LOOP;
 END LOOP;
 FOR v IN SELECT value FROM jsonb_array_elements(f->'accounts') LOOP
  account:=(v->>'id')::uuid;employee:=pg_temp.capacity_id('person',v->>'employee');
  INSERT INTO public.ihr_leave_accounts(id,employee_id,year,period_start,period_end,policy_id,timezone,opening_reconciled,opening_as_of,opening_source_id,created_at)
  VALUES(account,employee,(v->>'year')::int,make_date((v->>'year')::int,1,1),make_date((v->>'year')::int+1,1,1),policy,'Etc/UTC',true,make_date((v->>'year')::int,1,1),pg_temp.capacity_id('opening',v->>'id'),epoch);
  INSERT INTO public.ihr_leave_ledger(id,account_id,effective_date,kind,allowance_delta,source_kind,source_id,source_event,created_at)
  VALUES(pg_temp.capacity_id('grant-ledger',v->>'id'),account,make_date((v->>'year')::int,1,1),'annual_grant',5400,'annual_account',account,'grant',epoch);
 END LOOP;
 FOR v IN SELECT value FROM jsonb_array_elements(f->'requests') LOOP
  request:=(v->>'id')::uuid;employee:=pg_temp.capacity_id('person',v->>'employee');approver:=pg_temp.capacity_id('person',v->>'approver');account:=(v->>'account')::uuid;
  at_time:=make_date((v->>'year')::int,1,1)::timestamp AT TIME ZONE 'Etc/UTC';
  -- Historical calculator is owner setup only. It validates all original calendar, policy and account rules.
  q:=private.ihr_leave_quote_v1(employee,jsonb_build_object('start_date',v->>'start','end_date',v->>'end','duration',v->'duration','reason','Fictional capacity request'),at_time);
  IF (q->>'totalMinutes')::int<>(v->>'total')::int OR jsonb_array_length(q->'days')<>jsonb_array_length(v->'days') THEN RAISE EXCEPTION 'Generator and SQL quote disagree'; END IF;
  INSERT INTO public.ihr_leave_requests(id,employee_id,status,start_date,end_date,duration,total_minutes,reason,approver_id,approver_name,assignment_id,assignment_version,policy_id,policy_version,member_version,quote_fingerprint,source_snapshot,source_kind,source_id,submitted_at,created_by)
  SELECT request,employee,'submitted',(v->>'start')::date,(v->>'end')::date,v->'duration',(v->>'total')::int,'Fictional capacity request',approver,u.full_name,ar.id,ar.version,policy,p.version,m.version,q->>'fingerprint',
  jsonb_build_object('quote',q,'member',to_jsonb(m),'policy',to_jsonb(p),'assignment',to_jsonb(ar)),'submission',request,at_time,employee
  FROM public.ihr_leave_members m JOIN public.ihr_leave_policies p ON p.id=m.active_policy_id JOIN public.ihr_leave_approvers ar ON ar.employee_id=m.user_id JOIN public.users u ON u.id=ar.approver_id WHERE m.user_id=employee;
  FOR d IN SELECT value FROM jsonb_array_elements(q->'days') LOOP
   IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(v->'days') x WHERE x->>'date'=d->>'date' AND (x->>'scheduled')::int=(d->>'scheduledMinutes')::int AND (x->>'charged')::int=(d->>'chargedMinutes')::int) THEN RAISE EXCEPTION 'Generator and SQL immutable day disagree'; END IF;
   INSERT INTO public.ihr_leave_request_days(request_id,day,scheduled_minutes,charged_minutes,exclusion,account_id,source_snapshot)
   VALUES(request,(d->>'date')::date,(d->>'scheduledMinutes')::int,(d->>'chargedMinutes')::int,d->>'exclusion',(d->>'accountId')::uuid,private.ihr_leave_day_snapshot(employee,(d->>'date')::date));
  END LOOP;
  SELECT * INTO STRICT a FROM public.ihr_leave_accounts WHERE id=account;
  INSERT INTO public.ihr_leave_request_allocations VALUES(request,account,a.year,a.period_start,a.period_end,a.timezone,(v->>'total')::int,a.version);
  INSERT INTO public.ihr_leave_occupancy SELECT employee,day,request FROM public.ihr_leave_request_days WHERE request_id=request AND charged_minutes>0;
  IF v ? 'historyCycles' AND NOT EXISTS(SELECT 1 FROM public.ihr_leave_policies p WHERE p.id=policy AND p.cancellation_rules_confirmed AND p.cancellation_mode='whole_request' AND p.cancellation_allow_past AND p.cancellation_allow_repeat_declined AND p.cancellation_reason_required) THEN RAISE EXCEPTION 'Dense history requires explicit repeat-declined cancellation policy'; END IF;
  step_index:=0;attempt_number:=0;
  FOR step IN SELECT jsonb_array_elements_text(v->'transitions') LOOP
   reserved:=0;used:=0;ledger_kind:=NULL;next_status:=NULL;event_name:=step;event_actor:=employee;event_reason:=NULL;
   event_key:=(v->>'id')||':'||CASE WHEN v ? 'historyCycles' THEN step_index::text||':' ELSE '' END||step;
   CASE step
    WHEN 'submitted' THEN ledger_kind:='reservation';reserved:=(v->>'total')::int;
    WHEN 'approved' THEN ledger_kind:='approval';reserved:=-(v->>'total')::int;used:=(v->>'total')::int;next_status:='approved';event_actor:=approver;
    WHEN 'rejected' THEN event_reason:='Fictional rejection';ledger_kind:='rejection';reserved:=-(v->>'total')::int;next_status:='rejected';event_actor:=approver;
    WHEN 'withdrawn' THEN ledger_kind:='withdrawal';reserved:=-(v->>'total')::int;next_status:='withdrawn';
    WHEN 'cancellation_requested' THEN
     next_status:='cancellation_pending';event_reason:='Fictional cancellation';attempt_number:=attempt_number+1;
     attempt:=pg_temp.capacity_id('attempt',(v->>'id')||CASE WHEN attempt_number=1 THEN '' ELSE ':'||attempt_number::text END);
     INSERT INTO private.ihr_leave_cancellation_attempts(id,request_id,attempt_number,requested_by,requested_at,reason,approver_id,approver_name,assignment_id,assignment_version,policy_id,policy_version,source_snapshot)
     SELECT attempt,request,attempt_number,employee,at_time,'Fictional cancellation',approver,u.full_name,ar.id,ar.version,policy,1,jsonb_build_object('policy',to_jsonb(p),'assignment',to_jsonb(ar))
     FROM public.ihr_leave_approvers ar JOIN public.users u ON u.id=ar.approver_id CROSS JOIN public.ihr_leave_policies p WHERE ar.employee_id=employee AND p.id=policy;
    WHEN 'cancellation_declined' THEN
     next_status:='approved';event_actor:=approver;event_reason:='Fictional cancellation declined';
     INSERT INTO private.ihr_leave_cancellation_decisions VALUES(attempt,'declined',approver,at_time,event_reason);
    WHEN 'cancellation_accepted' THEN ledger_kind:='cancellation';used:=-(v->>'total')::int;next_status:='cancelled';event_actor:=approver;
     INSERT INTO private.ihr_leave_cancellation_decisions VALUES(attempt,'accepted',approver,at_time,NULL);
   END CASE;
   IF ledger_kind IS NOT NULL THEN
    reversal_ledger:=pg_temp.capacity_id('ledger',(v->>'id')||':'||step);
    INSERT INTO public.ihr_leave_ledger(id,account_id,effective_date,kind,reserved_delta,used_delta,source_kind,source_id,source_event,actor_id,created_at)
    VALUES(reversal_ledger,account,(v->>'start')::date,ledger_kind,reserved,used,'request',request,coalesce(next_status,'submitted'),event_actor,at_time);
    IF step='approved' THEN original_ledger:=reversal_ledger; END IF;
    IF step='cancellation_accepted' THEN INSERT INTO private.ihr_leave_charge_reversals VALUES(request,account,attempt,original_ledger,reversal_ledger,(v->>'total')::int); END IF;
   END IF;
   IF next_status IN('rejected','withdrawn','cancelled') THEN DELETE FROM public.ihr_leave_occupancy WHERE request_id=request; END IF;
   IF next_status IS NOT NULL THEN UPDATE public.ihr_leave_requests SET status=next_status,version=version+1 WHERE id=request; END IF;
   INSERT INTO private.ihr_leave_request_events(id,request_id,actor_id,event,at_time,data)
   VALUES(pg_temp.capacity_id('event',event_key),request,event_actor,event_name,at_time,jsonb_strip_nulls(jsonb_build_object('reason',event_reason,'attemptId',CASE WHEN step LIKE 'cancellation_%' THEN attempt END)));
   step_index:=step_index+1;
   at_time:=at_time+interval '1 second';
  END LOOP;
 END LOOP;
 -- Historical accounts are provisioned while eligible, then the five former employees are explicitly deactivated.
 UPDATE public.ihr_leave_members SET active=false WHERE user_id IN(SELECT (p->>'id')::uuid FROM jsonb_array_elements(f->'people') p WHERE (p->>'n')::int>500);
 UPDATE public.users SET is_active=false WHERE id IN(SELECT (p->>'id')::uuid FROM jsonb_array_elements(f->'people') p WHERE (p->>'n')::int>500);
END;
$fixture$;
ANALYZE public.ihr_leave_requests;
ANALYZE public.ihr_leave_request_days;
ANALYZE public.ihr_leave_request_allocations;
ANALYZE public.ihr_leave_occupancy;
ANALYZE public.ihr_leave_ledger;
ANALYZE public.ihr_leave_accounts;
ANALYZE public.ihr_leave_approvers;
ANALYZE public.ihr_leave_access_grants;
ANALYZE private.ihr_leave_request_events;
ANALYZE private.ihr_leave_cancellation_attempts;
