-- Final composed assertions. Run only in the independently guarded disposable lane.
BEGIN;
DO $fixture$ BEGIN
 IF current_database() NOT IN ('pilot_co_test','pilot_co_rollout_test') OR current_user<>'postgres'
 OR (SELECT count(*) FROM public.co_fixture_identity_v1)<>1
 OR NOT EXISTS(SELECT 1 FROM public.pilot_fixture_marker WHERE purpose='disposable-pilot-ci')
 THEN RAISE EXCEPTION 'Bound CO disposable fixture required'; END IF;
END $fixture$;
DO $audiences$ DECLARE f record; t record; BEGIN
 FOR f IN SELECT p.oid,p.proname,n.nspname,expected.signature FROM (VALUES
  ('private.co_actor_v1()'),
  ('private.co_allocation_signature_v1(jsonb)'),
  ('private.co_base_report_context_v1(uuid,date,uuid,jsonb)'),
  ('private.co_build_delivery_generation_v1(uuid,bigint,uuid,uuid)'),
  ('private.co_build_plan_v1(uuid,text,jsonb)'),
  ('private.co_closure_facts_v1(uuid,uuid,jsonb,jsonb)'),
  ('private.co_command_begin_v1(uuid,text,jsonb)'),
  ('private.co_command_commit_v1(uuid,jsonb)'),
  ('private.co_command_finished_v1()'),
  ('private.co_command_guard_v1()'),
  ('private.co_command_reconcile_v1(uuid,boolean)'),
  ('private.co_customer_state_guard_v1()'),
  ('private.co_delivered_line_quantity_v1(uuid)'),
  ('private.co_delivery_progress_v1(uuid)'),
  ('private.co_draft_report_v1(uuid,jsonb,jsonb)'),
  ('private.co_effective_allocation_signature_v1(uuid)'),
  ('private.co_evidence_begin_v1(uuid,text,jsonb)'),
  ('private.co_evidence_draft_v1(private.co_drafts,bigint,bigint)'),
  ('private.co_evidence_guard_v1()'),
  ('private.co_evidence_json_v1(private.co_evidence)'),
  ('private.co_evidence_matches_v1(uuid,jsonb)'),
  ('private.co_evidence_object_v1(private.co_evidence,uuid,text,bigint,text,text)'),
  ('private.co_evidence_path_v1(private.co_evidence)'),
  ('private.co_evidence_reconcile_v1(uuid,boolean,boolean)'),
  ('private.co_generation_append_v1()'),
  ('private.co_hash_v1(jsonb)'),
  ('private.co_identity_guard_v1()'),
  ('private.co_immutable_v1()'),
  ('private.co_input_date_v1(jsonb,boolean)'),
  ('private.co_input_object_v1(jsonb,text[],text[])'),
  ('private.co_input_price_v1(jsonb)'),
  ('private.co_input_quantity_v1(jsonb)'),
  ('private.co_input_text_v1(jsonb,boolean)'),
  ('private.co_input_uuid_v1(jsonb,boolean)'),
  ('private.co_input_version_v1(jsonb)'),
  ('private.co_link_evidence_v1(uuid,uuid,uuid,uuid,bigint,uuid)'),
  ('private.co_lock_customer_v1(uuid,bigint)'),
  ('private.co_materialize_generation_v1(uuid,bigint,uuid,jsonb,uuid,jsonb)'),
  ('private.co_money_v1(numeric)'),
  ('private.co_monthly_plan_v1(uuid,text,jsonb)'),
  ('private.co_monthly_sources_v1(uuid)'),
  ('private.co_monthly_transaction_v1(uuid,text,jsonb)'),
  ('private.co_normalize_sku_v1(text)'),
  ('private.co_order_snapshot_v1(uuid)'),
  ('private.co_orders_transaction_v1(uuid,text,jsonb)'),
  ('private.co_period_signature_v1(jsonb,text)'),
  ('private.co_plan_summary_v1(jsonb,boolean)'),
  ('private.co_prepare_sj_draft_v1()'),
  ('private.co_preview_header_v1(jsonb)'),
  ('private.co_preview_plan_v1(text,jsonb)'),
  ('private.co_publish_reviewed_v1(uuid,uuid,uuid,text,jsonb,text)'),
  ('private.co_read_actor_v1()'),
  ('private.co_read_allocations_v1(uuid,uuid,uuid)'),
  ('private.co_read_audit_leaves_v1(jsonb)'),
  ('private.co_read_audit_matches_v1(private.co_audit_events,uuid)'),
  ('private.co_read_batches_v1(uuid,uuid,uuid)'),
  ('private.co_read_context_link_v1(jsonb)'),
  ('private.co_read_customer_v1(uuid,text)'),
  ('private.co_read_date_v1(date)'),
  ('private.co_read_delivery_v1(uuid)'),
  ('private.co_read_freshness_v1(uuid,date)'),
  ('private.co_read_lock_v1(uuid,text)'),
  ('private.co_read_month_v1(text)'),
  ('private.co_read_order_summary_v1(uuid)'),
  ('private.co_read_order_v1(uuid)'),
  ('private.co_read_page_v1(jsonb,integer,integer,jsonb)'),
  ('private.co_read_report_context_v1(uuid)'),
  ('private.co_read_report_header_v1(uuid,text)'),
  ('private.co_read_return_header_v1(uuid,text)'),
  ('private.co_read_revision_generation_v1(uuid)'),
  ('private.co_read_sj_draft_v1(uuid)'),
  ('private.co_replay_v1(jsonb)'),
  ('private.co_report_context_v1(uuid,date,uuid,jsonb)'),
  ('private.co_required_months_v1(jsonb,jsonb,date,boolean)'),
  ('private.co_revision_line_guard_v1()'),
  ('private.co_sales_metric_facts_v2(uuid,date,date,text)'),
  ('private.co_sales_scope_v2()'),
  ('private.co_sold_input_v1(jsonb)'),
  ('private.co_source_proposal_v1(uuid,text,jsonb)'),
  ('private.co_source_snapshot_v1()'),
  ('private.co_sources_v1(uuid)'),
  ('private.co_stock_key_v1(uuid,text,text,uuid,uuid)'),
  ('private.co_validate_delivery_change_v1(uuid,uuid,uuid,jsonb)'),
  ('private.co_validate_return_lines_v1(uuid,jsonb)'),
  ('private.co_validate_sj_lines_v1(uuid,jsonb)'),
  ('private.co_write_order_lines_v1(uuid,uuid,jsonb)'),
  ('public.pilot_co_customer_batches_v1(uuid,uuid,text,integer,integer)'),
  ('public.pilot_co_customer_stock_v1(uuid,date,text,text,integer,integer)'),
  ('public.pilot_co_detail_section_v1(uuid,text,uuid,text,text,integer,integer,text)'),
  ('public.pilot_co_detail_v1(uuid,text)'),
  ('public.pilot_co_evidence_attest_v1(uuid,uuid,uuid,text,bigint,text,text)'),
  ('public.pilot_co_evidence_context_v1(uuid,text)'),
  ('public.pilot_co_evidence_selection_v1(uuid,uuid,text)'),
  ('public.pilot_co_evidence_transaction_v1(uuid,text,jsonb)'),
  ('public.pilot_co_evidence_v1(uuid)'),
  ('public.pilot_co_page_v1(text,text,integer,integer,uuid)'),
  ('public.pilot_co_preview_allocations_v1(text,jsonb,text,text,uuid,integer,integer)'),
  ('public.pilot_co_preview_impacts_v1(text,jsonb,text,text,integer,integer)'),
  ('public.pilot_co_preview_v1(text,jsonb)'),
  ('public.pilot_co_report_allocations_v1(uuid,text,uuid,text,integer,integer)'),
  ('public.pilot_co_report_months_v1(uuid)'),
  ('public.pilot_co_report_rows_v1(uuid,text,text,text,text,integer,integer,uuid)'),
  ('public.pilot_co_report_v1(uuid,text,text)'),
  ('public.pilot_co_reports_page_v1(uuid,text,text,integer,integer)'),
  ('public.pilot_co_return_v1(uuid,uuid,text,text,text,integer,integer)'),
  ('public.pilot_co_stock_movements_v1(uuid,uuid,date,integer,integer)'),
  ('public.pilot_co_transaction_v1(uuid,text,jsonb)'),
  ('public.pilot_procurement_access_v1()'),
  ('public.pilot_reconcile_co_evidence_v1(uuid,boolean)'),
  ('public.pilot_reconcile_co_v1(uuid,boolean)'),
  ('public.pilot_sales_metric_months_v2(uuid,text)'),
  ('public.pilot_sales_metrics_v2(uuid,date,date,text,text,integer,integer)')) expected(signature) LEFT JOIN pg_proc p ON p.oid=to_regprocedure(expected.signature) LEFT JOIN pg_namespace n ON n.oid=p.pronamespace LOOP
  IF f.oid IS NULL THEN RAISE EXCEPTION 'Missing reviewed CO function: %',f.signature; END IF;
  IF has_function_privilege('anon',f.oid,'EXECUTE') THEN RAISE EXCEPTION 'Anonymous CO function exposure: %',f.proname; END IF;
  IF f.nspname='private' AND has_function_privilege('authenticated',f.oid,'EXECUTE') THEN RAISE EXCEPTION 'Private CO function exposure'; END IF;
  IF has_function_privilege('service_role',f.oid,'EXECUTE') IS DISTINCT FROM (f.proname='pilot_co_evidence_attest_v1') THEN RAISE EXCEPTION 'Unexpected service audience: %',f.proname; END IF;
  IF f.nspname='public' AND has_function_privilege('authenticated',f.oid,'EXECUTE') IS DISTINCT FROM (f.proname<>'pilot_co_evidence_attest_v1') THEN RAISE EXCEPTION 'Unexpected authenticated audience'; END IF;
 END LOOP;
 FOR t IN SELECT c.oid,c.relname,c.relrowsecurity,expected.name FROM (VALUES
  ('private.co_audit_events'),
  ('private.co_commands'),
  ('private.co_customer_state'),
  ('private.co_delivery_heads'),
  ('private.co_delivery_revision_lines'),
  ('private.co_delivery_revisions'),
  ('private.co_drafts'),
  ('private.co_evidence'),
  ('private.co_evidence_verifications'),
  ('private.co_order_lines'),
  ('private.co_orders'),
  ('private.co_replay_generations'),
  ('private.co_report_draft_lines'),
  ('private.co_report_evidence'),
  ('private.co_report_heads'),
  ('private.co_report_revision_lines'),
  ('private.co_report_revisions'),
  ('private.co_return_heads'),
  ('private.co_return_revision_lines'),
  ('private.co_return_revisions'),
  ('private.co_sale_allocations'),
  ('private.co_stock_batches'),
  ('private.co_stock_keys'),
  ('private.co_stock_movements')) expected(name) LEFT JOIN pg_class c ON c.oid=to_regclass(expected.name) LOOP
  IF t.oid IS NULL THEN RAISE EXCEPTION 'Missing reviewed CO table: %',t.name; END IF;
  IF NOT t.relrowsecurity OR has_table_privilege('anon',t.oid,'SELECT,INSERT,UPDATE,DELETE') OR has_table_privilege('authenticated',t.oid,'SELECT,INSERT,UPDATE,DELETE') OR has_table_privilege('service_role',t.oid,'SELECT,INSERT,UPDATE,DELETE') THEN RAISE EXCEPTION 'CO table audience/RLS drift: %',t.relname; END IF;
 END LOOP;
 IF has_sequence_privilege('service_role','private.co_delivery_heads_original_creation_order_seq','USAGE,SELECT,UPDATE') THEN RAISE EXCEPTION 'CO sequence service exposure'; END IF;
END $audiences$;
SELECT 'CO_FINAL_AUDIENCES_PASSED';
ROLLBACK;
