\set ON_ERROR_STOP on
BEGIN;
DO $$ BEGIN IF current_database()<>'pilot_test' OR NOT EXISTS(SELECT 1 FROM public.pilot_fixture_marker WHERE purpose='disposable-pilot-ci') THEN RAISE EXCEPTION 'Disposable fixture required'; END IF; END $$;
CREATE FUNCTION pg_temp.ok(ok boolean,message text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION 'ASSERT: %',message; END IF; END $$;
CREATE FUNCTION pg_temp.denied(statement text,code text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE statement; EXCEPTION WHEN OTHERS THEN IF SQLSTATE=code THEN RETURN; ELSE RAISE; END IF; END; RAISE EXCEPTION 'Expected %: %',code,statement; END $$;
CREATE FUNCTION pg_temp.uid(n int) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT md5('owner-user-'||n)::uuid $$;
CREATE FUNCTION pg_temp.store(n int) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT md5('owner-store-'||n)::uuid $$;
SELECT pg_temp.ok((SELECT sales_person_id_at_creation=pg_temp.uid(2) FROM public.purchase_orders WHERE id=md5('owner-po-1')::uuid),'existing manager owner receives test PO credit, secondary mapping ignored');
SELECT pg_temp.ok((SELECT sales_person_id_at_creation=pg_temp.uid(4) FROM public.purchase_orders WHERE id=md5('owner-po-2')::uuid),'existing salesperson owner receives test PO credit');
SELECT pg_temp.ok((SELECT bool_and(sales_attribution_state='unassigned' AND sales_person_id_at_creation IS NULL) FROM public.purchase_orders WHERE customer_id=pg_temp.store(3)),'missing canonical mapping stays explicitly unassigned');
SELECT pg_temp.ok((SELECT count(*)=4 FROM private.pilot_store_credit_corrections_v1),'all corrected rows are audited');
SELECT pg_temp.ok((SELECT total_value=100 AND status='confirm' AND order_date='2026-10-01' FROM public.purchase_orders WHERE id=md5('owner-po-1')::uuid),'PO amount/status/date intact');
SELECT pg_temp.ok(NOT has_table_privilege('authenticated','public.customer_manager_assignments','INSERT,UPDATE,DELETE'),'assignment writes use checked RPC only');
SELECT pg_temp.ok(NOT has_function_privilege('anon','public.pilot_assign_store_owner_v1(uuid,uuid,uuid,bigint)','EXECUTE'),'anonymous assignment denied');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT pg_temp.ok(private.pilot_can_access_customer(pg_temp.store(1)) AND private.pilot_can_access_customer(pg_temp.store(2)),'manager can access own and direct salesperson-owned stores');
SELECT pg_temp.ok(NOT private.pilot_can_access_customer(pg_temp.store(3)),'manager cannot access unassigned store');
SELECT pg_temp.ok(private.pilot_can_schedule(pg_temp.store(2),pg_temp.uid(4)),'current supervisor retains team scheduling');
SELECT pg_temp.denied(format('SELECT public.pilot_assign_store_owner_v1(%L,%L,NULL,NULL)',pg_temp.store(4),pg_temp.uid(2)),'42501');
SELECT pg_temp.denied(format('SELECT private.pilot_schedule_authority_v1(''approve_request'',%L::jsonb)',jsonb_build_object('sales_person_id',pg_temp.uid(2),'customer_id',pg_temp.store(1))),'42501');
SELECT pg_temp.ok((SELECT sum(total_value)=215 AND count(*)=2 FROM private.pilot_canonical_sales_source_v1('2026-09-01','2026-11-01')),'manager own plus team credit counts once; linked legacy amount preserved');
SELECT pg_temp.ok((SELECT count(*)=1 FROM private.pilot_canonical_sales_source_v1('2026-09-01','2026-11-01') WHERE sales_person_id=pg_temp.uid(2) AND total_value=15),'linked PO attributed to owner using original legacy amount/date');
SELECT pg_temp.ok((public.pilot_manager_customers_v1(auth.uid(),'2026-01-01','2026-10-10',1,100)->>'total')::int=2,'manager customer list includes salesperson-owned store');
SELECT pg_temp.denied(format('SELECT public.pilot_order_transaction(%L,''create_po'',%L::jsonb)',gen_random_uuid(),jsonb_build_object('customer_id',pg_temp.store(1),'po_number','DENIED','items',jsonb_build_array(jsonb_build_object('product_name','test','quantity',1,'unit_price',1)))),'42501');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(5)::text,true);
SELECT pg_temp.ok(NOT private.pilot_can_access_customer(pg_temp.store(1)),'hidden secondary assignment grants no owner access');
SELECT pg_temp.ok((SELECT count(*)=0 FROM private.pilot_canonical_sales_source_v1('2026-09-01','2026-11-01')),'old linked submitter does not double-count owner credit');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.ok(private.pilot_can_access_customer(pg_temp.store(2)),'salesperson owns store');
SELECT pg_temp.ok((SELECT count(*)=1 AND sum(total_value)=200 FROM private.pilot_canonical_sales_source_v1('2026-09-01','2026-11-01')),'salesperson sees only own snapshot');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(1)::text,true);
SELECT pg_temp.ok((SELECT count(*)=4 AND sum(total_value)=915 FROM private.pilot_canonical_sales_source_v1('2026-09-01','2026-11-01')),'leadership sees each PO exactly once including explicit unassigned');
SELECT pg_temp.denied(format('SELECT public.pilot_assign_store_owner_v1(%L,%L,NULL,NULL)',pg_temp.store(4),pg_temp.uid(6)),'22023');
SELECT pg_temp.denied(format('SELECT public.pilot_assign_store_owner_v1(%L,%L,NULL,NULL)',pg_temp.store(4),pg_temp.uid(7)),'22023');
SELECT public.pilot_assign_store_owner_v1(pg_temp.store(4),pg_temp.uid(4),NULL,NULL);
SELECT public.pilot_assign_store_owner_v1(pg_temp.store(5),pg_temp.uid(4),NULL,NULL);
SELECT pg_temp.ok((SELECT count(*)=3 FROM public.customer_manager_assignments WHERE manager_id=pg_temp.uid(4)),'one person can own multiple stores');
SELECT pg_temp.denied(format('SELECT public.pilot_assign_store_owner_v1(%L,%L,NULL,NULL)',pg_temp.store(4),pg_temp.uid(2)),'40001');
SELECT public.pilot_assign_store_owner_v1(pg_temp.store(2),pg_temp.uid(3),md5('owner-assignment-2')::uuid,1);
SELECT pg_temp.denied(format('SELECT public.pilot_assign_store_owner_v1(%L,%L,%L,1)',pg_temp.store(2),pg_temp.uid(2),md5('owner-assignment-2')::uuid),'40001');
SELECT public.pilot_assign_store_owner_v1(pg_temp.store(5),NULL,(SELECT id FROM public.customer_manager_assignments WHERE customer_id=pg_temp.store(5)),1);
SELECT pg_temp.ok((SELECT manager_id IS NULL AND version=2 FROM public.customer_manager_assignments WHERE customer_id=pg_temp.store(5)),'clear retains a versioned empty assignment');
SELECT pg_temp.denied(format('SELECT public.pilot_assign_store_owner_v1(%L,%L,NULL,NULL)',pg_temp.store(5),pg_temp.uid(2)),'40001');
RESET ROLE;
SELECT pg_temp.ok((SELECT sales_person_id_at_creation=pg_temp.uid(4) FROM public.purchase_orders WHERE id=md5('owner-po-2')::uuid),'later assignment leaves past snapshots fixed');
SELECT pg_temp.denied(format('UPDATE public.purchase_orders SET sales_person_id_at_creation=%L WHERE id=%L',pg_temp.uid(3),md5('owner-po-2')::uuid),'23514');
UPDATE public.users SET manager_id=pg_temp.uid(3) WHERE id=pg_temp.uid(4);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT pg_temp.ok(NOT private.pilot_can_access_customer(pg_temp.store(4)),'former reporting manager loses store scope immediately');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(3)::text,true);
SELECT pg_temp.ok(private.pilot_can_access_customer(pg_temp.store(4)),'new reporting manager gains current salesperson store scope');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(6)::text,true);
DO $$ DECLARE result jsonb; po uuid; BEGIN
 result:=public.pilot_order_transaction(gen_random_uuid(),'create_po',jsonb_build_object('customer_id',pg_temp.store(1),'po_number','OWNER-NEW-MANAGER','items',jsonb_build_array(jsonb_build_object('product_name','Synthetic','quantity',1,'unit_price',25))));
 po:=(result->>'id')::uuid;
 PERFORM pg_temp.ok((SELECT sales_person_id_at_creation=pg_temp.uid(2) FROM public.purchase_orders WHERE id=po),'new admin PO snapshots current manager owner');
 result:=public.pilot_order_transaction(gen_random_uuid(),'create_po',jsonb_build_object('customer_id',pg_temp.store(2),'po_number','OWNER-NEW-REASSIGNED','items',jsonb_build_array(jsonb_build_object('product_name','Synthetic','quantity',1,'unit_price',25))));
 po:=(result->>'id')::uuid;
 PERFORM pg_temp.ok((SELECT sales_person_id_at_creation=pg_temp.uid(3) FROM public.purchase_orders WHERE id=po),'new admin PO snapshots reassigned owner');
END $$;
RESET ROLE;
SELECT pg_temp.ok((SELECT count(*)=4 FROM private.pilot_store_owner_audit_v1),'assignment changes audited once each');
SELECT 'STORE_OWNER_SCOPE_CREDIT_AND_AUDIT_PASSED';
ROLLBACK;
