import { expect, test, vi } from 'vitest';
import { screen, fireEvent, waitFor } from '@testing-library/react';
import { store, mount, wire, customer, draftId, id, month, hash, reportImpact } from './report-ui-harness';
import COCorrectionDialog from '../../src/components/co/COCorrectionDialog';
import { useCOTransactionSender } from '../../src/lib/co/transactions';
function Review({ onAccepted = async () => true }: {
    onAccepted?: any;
}) { const sender = useCOTransactionSender({ formScope: 'test-review', customerId: customer }); return <COCorrectionDialog operation="correct_report" customerId={customer} selectedMonth={month} source={{ draft_id: draftId, expected_draft_version: '1', expected_customer_version: '1', eligible_set_fingerprint: hash, report_head_id: id(4), original_revision_id: id(5), expected_report_version: '1' }} sender={sender} current={() => wire.actor} onAccepted={onAccepted} onClose={() => { }} returnFocus={null}/>; }
test('reason and complete exact reopen set require a new final fingerprint before a single atomic apply', async () => { const s = store(); s.rows[0].sold_quantity = '70'; s.impacts.report = [reportImpact()]; s.impacts.reopen = Array.from({ length: 101 }, (_, i) => ({ co_id: id(8000 + i), expected_co_version: String(i + 1), remaining_quantity: '0', pending_quantity: '1', missing_month_count: '1' })); let accepted = 0; mount(<Review onAccepted={async () => { accepted++; return true; }}/>); expect((await screen.findByRole('button', { name: 'Tinjau semua dampak' }) as HTMLButtonElement).disabled).toBe(true); fireEvent.change(screen.getByLabelText('Alasan perubahan'), { target: { value: 'Correct source evidence' } }); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); await screen.findByText(/101 CO perlu dibuka ulang/); expect(screen.queryByRole('button', { name: 'Terapkan perubahan' })).toBeNull(); fireEvent.click(screen.getByRole('checkbox', { name: /Saya menyetujui pembukaan ulang tepat 101 CO/ })); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); await screen.findByRole('button', { name: 'Terapkan perubahan' }); const button = screen.getByRole('button', { name: 'Terapkan perubahan' }); fireEvent.click(button); fireEvent.click(button); await waitFor(() => expect(accepted).toBe(1)); expect(s.commands).toHaveLength(1); expect(s.commands[0].payload.acknowledged_reopen_orders).toHaveLength(101); expect(s.commands[0].payload.original_revision_id).toBe(id(5)); expect(s.previewCount).toBe(2); });
test('posted periods gaining new SKUs are completion requirements as well as missing months', async () => { const s = store(); s.rows[0].sold_quantity = '70'; s.impacts.issue = [{ code: 'CO_REPORT_INCOMPLETE', report_month: '2026-10-01', stock_key_id: id(1602) }]; s.impacts.missing_month = [{ report_month: '2026-08-01', reason: 'missing', head_id: null, coverage_through_date: null }]; mount(<Review />); fireEvent.change(await screen.findByLabelText('Alasan perubahan'), { target: { value: 'Backdated source' } }); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); expect(await screen.findByRole('button', { name: 'Lengkapi periode 2026-10' })).toBeTruthy(); expect(screen.getByRole('button', { name: 'Lengkapi periode 2026-08' })).toBeTruthy(); expect(screen.queryByRole('button', { name: 'Terapkan perubahan' })).toBeNull(); });
test('shared SJ owner exposes reviewed publication from a canonical prepared draft', async () => { const { default: CODeliveryDialog } = await import('../../src/components/co/CODeliveryDialog'); const s = store(); s.rows[0].sold_quantity = '70'; const co = { id: id(10), customer_id: customer, customer_name: 'Store A', co_number: 'CO-1', status: 'active', order_date: '2026-09-01', expected_delivery_date: null, notes: null, co_version: '1', customer_version: '1', generation_id: null, sales_person_name: null, sales_person_id_at_creation: null, sales_assignment_source_id: null, sales_attributed_at: '2026-09-01T00:00:00Z', sales_attribution_state: 'unassigned', summary: { ordered_quantity: '100', delivered_quantity: '0', resolved_undelivered_quantity: '0', pending_quantity: '100', delivery_progress: 'not_started', planned_value: '1000000', sold_quantity: '0', revenue: '0', returned_quantity: '0', remaining_quantity: '0' }, last_report_month: null, coverage_through_date: null, reporting_freshness: s.header().reporting_freshness }; const base = s.handle; wire.handler = async (n: string, a: any) => { if (n === 'pilot_co_detail_v1')
    return { data: { version: '1', as_of: '2026-10-09T00:00:00Z', co, allowed_operations: ['post_sj', 'save_sj_draft', 'correct_sj'], close_blockers: { stock_remains: false, undelivered_remains: true, missing_month_count: '1' } }, error: null }; if (n === 'pilot_co_detail_section_v1') {
    const rows = a.p_section === 'lines' ? [{ id: id(11), co_id: co.id, customer_id: customer, stock_key_id: id(1001), display_sku: 'SKU-1', product_name: 'Item 1', product_id: null, ordered_quantity: '100', resolved_undelivered_quantity: '0', delivered_quantity: '0', pending_quantity: '100', unit_price: '10000', removable: true }] : a.p_section === 'sj_drafts' ? [{ id: draftId, co_id: co.id, customer_id: customer, draft_version: '1', mode: 'delivery_correction', sj_number: 'SJ-1', sj_date: '2026-09-01', received_date: null, notes: null, bound_co_version: '1', bound_customer_version: '1', bound_delivery_head_id: id(12), bound_delivery_revision_id: id(13), bound_delivery_version: '2', posted_delivery_head_id: null, line_count: '1', consumed: false, bindings_current: true, preparation_ready: true }] : [{ id: id(11), co_line_id: id(11), co_id: co.id, customer_id: customer, draft_id: draftId, source_available: true, source_issue: null, stock_key_id: id(1001), display_sku: 'SKU-1', product_name: 'Item 1', unit_price: '10000', quantity: '70' }];
    return { data: { version: '1', as_of: '2026-10-09T00:00:00Z', co_id: co.id, customer_id: customer, co_version: '1', customer_version: '1', section: a.p_section, parent_id: a.p_parent_id, ...(a.p_section === 'sj_draft_lines' ? { draft_id: draftId, draft_version: '1' } : {}), total: '1', page: a.p_page, page_size: a.p_page_size, rows }, error: null };
} return base(n, a); }; mount(<CODeliveryDialog co={co as any} draftId={draftId} onClose={() => { }} returnFocus={null}/>); await waitFor(() => expect((screen.getByRole('button', { name: 'Tinjau perubahan SJ' }) as HTMLButtonElement).disabled).toBe(false)); fireEvent.click(screen.getByRole('button', { name: 'Tinjau perubahan SJ' })); fireEvent.change(await screen.findByLabelText('Alasan perubahan'), { target: { value: 'SJ replacement' } }); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); await waitFor(() => expect(wire.rpc.mock.calls.some(([n, a]) => n === 'pilot_co_preview_v1' && a.p_operation === 'correct_sj')).toBe(true)); const p = wire.rpc.mock.calls.find(([n, a]) => n === 'pilot_co_preview_v1' && a.p_operation === 'correct_sj')![1].p_payload; expect(p).toMatchObject({ action: 'replace', delivery_head_id: id(12), original_revision_id: id(13), expected_delivery_version: '2', draft_id: draftId, expected_draft_version: '1' }); });
test('completes missing and posted 602-row periods with exact context and original revision in one bundle', async () => { const primary = store(); primary.rows[0].sold_quantity = '70'; const downstream = store(602, '2026-10-01', id(30)); downstream.rows.forEach((r: any, i: number) => r.sold_quantity = i === 601 ? null : '0'); downstream.effective = { ...downstream.header(), id: id(40), status: 'posted', draft_id: null, draft_version: null, report_head_id: id(40), revision_id: id(41), report_version: '3', eligible_set_fingerprint: null, row_count: '601', entered_count: '601', missing_count: '0', complete: true, revenue: '0' }; const missing = store(1, '2026-08-01', id(50)); missing.draft = false; const previews: any[] = []; wire.handler = async (n: string, a: any) => { if (n === 'pilot_co_preview_v1') {
    previews.push(a.p_payload);
    const completed = a.p_payload.completed_report_drafts;
    primary.impacts.issue = completed.some((d: any) => d.draft_id === id(30)) ? [] : [{ code: 'CO_REPORT_INCOMPLETE', report_month: '2026-10-01', stock_key_id: id(1602) }];
    primary.impacts.missing_month = completed.some((d: any) => d.draft_id === id(50)) ? [] : [{ report_month: '2026-08-01', reason: 'missing', head_id: null, coverage_through_date: null }];
    return primary.handle(n, a);
} if (n === 'pilot_reconcile_co_v1') {
    const s = [primary, downstream, missing].find(s => s.receipt && s.receipt.id === a.__receiptId); /* Requests are issued sequentially; match the last actual write. */
    return last.handle(n, a);
} if (n === 'pilot_co_transaction_v1') {
    last = a.p_payload.draft_id === id(30) ? downstream : a.p_payload.draft_id === id(50) || a.p_payload.report_month === '2026-08-01' ? missing : primary;
    return last.handle(n, a);
} if (n === 'pilot_co_report_v1' || n === 'pilot_co_report_rows_v1')
    return (a.p_month === '2026-10-01' ? downstream : a.p_month === '2026-08-01' ? missing : primary).handle(n, a); return primary.handle(n, a); }; let last = primary; mount(<Review />); fireEvent.change(await screen.findByLabelText('Alasan perubahan'), { target: { value: 'Backdated correction' } }); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); fireEvent.click(await screen.findByRole('button', { name: 'Lengkapi periode 2026-10' })); await waitFor(() => expect((screen.getByRole('button', { name: 'Perbarui periode terhadap sumber usulan' }) as HTMLButtonElement).disabled).toBe(false)); fireEvent.click(screen.getByRole('button', { name: 'Perbarui periode terhadap sumber usulan' })); await screen.findByLabelText('Terjual Item 1'); for (let p = 1; p < 7; p++) {
    fireEvent.click(screen.getByRole('button', { name: 'Berikutnya' }));
    await screen.findByLabelText(`Terjual Item ${p * 100 + 1}`);
} fireEvent.change(screen.getByLabelText('Terjual Item 602'), { target: { value: '0' } }); fireEvent.click(screen.getByRole('button', { name: 'Gunakan draft periode lengkap' })); await screen.findByText(/Draft periode siap dalam paket: 2026-10/); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); fireEvent.click(await screen.findByRole('button', { name: 'Lengkapi periode 2026-08' })); await waitFor(() => expect((screen.getByRole('button', { name: 'Perbarui periode terhadap sumber usulan' }) as HTMLButtonElement).disabled).toBe(false)); fireEvent.click(screen.getByRole('button', { name: 'Perbarui periode terhadap sumber usulan' })); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '0' } }); fireEvent.click(screen.getByRole('button', { name: 'Gunakan draft periode lengkap' })); await screen.findByText(/2026-10, 2026-08/); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); await screen.findByRole('button', { name: 'Terapkan perubahan' }); const bundle = previews.at(-1).completed_report_drafts; expect(bundle.find((b: any) => b.draft_id === id(30))).toMatchObject({ original_revision_id: id(41), expected_report_version: '3', expected_draft_version: '3' }); expect(bundle.find((b: any) => b.draft_id === id(50))).not.toHaveProperty('original_revision_id'); expect(downstream.commands[0].payload.source_context.payload).not.toHaveProperty('completed_report_drafts'); expect(primary.commands).toHaveLength(0); expect(downstream.commands.every((c: any) => c.op === 'save_report_draft')).toBe(true); fireEvent.click(screen.getByRole('button', { name: 'Terapkan perubahan' })); await waitFor(() => expect(primary.commands).toHaveLength(1)); expect(primary.commands[0].payload.completed_report_drafts).toHaveLength(2); }, 20000);
test('posted SJ replacement is reachable and imports complete canonical original lines without ordinary conversion', async () => { const { deliveryFixture } = await import('./report-ui-harness'); const { default: CODetail } = await import('../../src/pages/athel/co/CODetail'); const s = deliveryFixture(101); mount(<CODetail />, `/athel/co/${id(10)}`); fireEvent.click(await screen.findByRole('button', { name: 'Siapkan pengganti SJ' })); await screen.findByLabelText('Jumlah dikirim Item 101'); fireEvent.click(screen.getByRole('button', { name: 'Simpan Draft SJ' })); await waitFor(() => expect(s.commands).toHaveLength(1)); expect(s.commands[0].payload).toMatchObject({ delivery_head_id: id(12), original_revision_id: id(13), expected_delivery_version: '2', expected_co_version: '1', expected_customer_version: '1' }); expect(s.commands[0].payload.lines).toHaveLength(101); expect(screen.queryByRole('button', { name: 'Post SJ' })).toBeNull(); expect(wire.rpc.mock.calls.filter(([n, a]) => n === 'pilot_co_detail_section_v1' && a.p_section === 'delivery_lines').some(([, a]) => a.p_page === 2)).toBe(true); });
test('posted SJ void is reachable, sends no replacement draft, and validates the canonical corrected head', async () => { const { deliveryFixture } = await import('./report-ui-harness'); const { default: CODetail } = await import('../../src/pages/athel/co/CODetail'); const s = deliveryFixture(); mount(<CODetail />, `/athel/co/${id(10)}`); fireEvent.click(await screen.findByRole('button', { name: 'Batalkan SJ dengan koreksi' })); fireEvent.change(await screen.findByLabelText('Alasan perubahan'), { target: { value: 'Void duplicate document' } }); fireEvent.click(screen.getByRole('button', { name: 'Tinjau semua dampak' })); fireEvent.click(await screen.findByRole('button', { name: 'Terapkan perubahan' })); await waitFor(() => expect(s.commands).toHaveLength(1)); expect(s.commands[0].payload).toMatchObject({ action: 'void', delivery_head_id: id(12), original_revision_id: id(13), expected_delivery_version: '2' }); expect(s.commands[0].payload).not.toHaveProperty('draft_id'); await waitFor(() => expect(screen.queryByLabelText('Alasan perubahan')).toBeNull()); expect(wire.rpc.mock.calls.some(([n, a]) => n === 'pilot_co_detail_section_v1' && a.p_section === 'deliveries' && a.p_parent_id === id(12))).toBe(true); });
test('superseded SJ selection fails closed during canonical preparation', async () => { const { deliveryFixture } = await import('./report-ui-harness'); const { default: CODetail } = await import('../../src/pages/athel/co/CODetail'); const s = deliveryFixture(); mount(<CODetail />, `/athel/co/${id(10)}`); const button = await screen.findByRole('button', { name: 'Siapkan pengganti SJ' }); s.stale = true; fireEvent.click(button); await screen.findByText(/Revisi SJ berubah/); expect(s.commands).toHaveLength(0); expect(screen.queryByLabelText('Jumlah dikirim Item 1')).toBeNull(); });
test('voided current SJ replacement starts with no resurrected quantities and cannot void twice', async () => { const { deliveryFixture } = await import('./report-ui-harness'); const { default: CODetail } = await import('../../src/pages/athel/co/CODetail'); const s = deliveryFixture(1, true); mount(<CODetail />, `/athel/co/${id(10)}`); const replace = await screen.findByRole('button', { name: 'Siapkan pengganti SJ' }); expect(screen.queryByRole('button', { name: 'Batalkan SJ dengan koreksi' })).toBeNull(); fireEvent.click(replace); await screen.findByDisplayValue('SJ-original'); expect(screen.queryByLabelText('Jumlah dikirim Item 1')).toBeNull(); fireEvent.change(screen.getByLabelText('Tambahkan sumber CO'), { target: { value: id(100) } }); expect((await screen.findByLabelText('Jumlah dikirim Item 1') as HTMLInputElement).value).toBe('0'); fireEvent.change(screen.getByLabelText('Jumlah dikirim Item 1'), { target: { value: '4' } }); fireEvent.click(screen.getByRole('button', { name: 'Simpan Draft SJ' })); await waitFor(() => expect(s.commands).toHaveLength(1)); expect(s.commands[0].payload.lines).toEqual([{ co_line_id: id(100), quantity: 4 }]); });
test('monthly correction dismissal is guarded by its existing report owner', async () => { const { default: COMonthlyReport } = await import('../../src/pages/athel/co/COMonthlyReport'); const s = store(); s.rows[0].sold_quantity = '70'; s.effective = { ...s.header(), id: id(4), status: 'posted', draft_id: null, draft_version: null, report_head_id: id(4), revision_id: id(5), report_version: '1', eligible_set_fingerprint: null, revenue: '700000' }; mount(<COMonthlyReport />); fireEvent.click(await screen.findByRole('button', { name: 'Siapkan revisi laporan' })); await waitFor(() => expect((screen.getByRole('button', { name: 'Tinjau koreksi laporan' }) as HTMLButtonElement).disabled).toBe(false)); fireEvent.click(screen.getByRole('button', { name: 'Tinjau koreksi laporan' })); fireEvent.change(await screen.findByLabelText('Alasan perubahan'), { target: { value: 'Keep correction reason' } }); fireEvent.click(screen.getByRole('button', { name: 'Kembali ke sumber' })); fireEvent.click(await screen.findByRole('button', { name: 'Tetap mengedit' })); expect(screen.getByDisplayValue('Keep correction reason')).toBeTruthy(); });
test('closed CO prepares only source-bound correction under correct_sj capability', async () => { const { deliveryFixture } = await import('./report-ui-harness'); const { default: CODetail } = await import('../../src/pages/athel/co/CODetail'); const s = deliveryFixture(); s.co.status = 'closed'; s.co.summary = { ...s.co.summary, ordered_quantity: '70', pending_quantity: '0', delivery_progress: 'complete', sold_quantity: '70', remaining_quantity: '0' }; s.allowed = ['correct_sj']; mount(<CODetail />, `/athel/co/${id(10)}`); fireEvent.click(await screen.findByRole('button', { name: 'Siapkan pengganti SJ' })); await screen.findByLabelText('Jumlah dikirim Item 1'); expect((screen.getByRole('button', { name: 'Simpan Draft SJ' }) as HTMLButtonElement).disabled).toBe(false); expect(screen.queryByRole('button', { name: 'Post SJ' })).toBeNull(); fireEvent.click(screen.getByRole('button', { name: 'Simpan Draft SJ' })); await waitFor(() => expect(s.commands).toHaveLength(1)); expect(s.commands[0].payload.delivery_head_id).toBe(id(12)); });
test('authoritative active without-history capability makes ordinary Post reachable', async () => { const { deliveryFixture } = await import('./report-ui-harness'); const { default: CODeliveryDialog } = await import('../../src/components/co/CODeliveryDialog'); const s = deliveryFixture(); s.allowed = ['edit_co', 'save_sj_draft', 'post_sj', 'save_report_draft', 'cancel_co', 'resolve_undelivered']; mount(<CODeliveryDialog co={s.co} onClose={() => { }} returnFocus={null}/>); fireEvent.change(await screen.findByLabelText('Nomor SJ'), { target: { value: 'New SJ' } }); fireEvent.change(screen.getByLabelText('Jumlah dikirim Item 1'), { target: { value: '1' } }); fireEvent.click(screen.getByRole('button', { name: 'Simpan Draft SJ' })); await waitFor(() => expect((screen.getByRole('button', { name: 'Post SJ' }) as HTMLButtonElement).disabled).toBe(false)); fireEvent.click(screen.getByRole('button', { name: 'Post SJ' })); await waitFor(() => expect(s.commands).toHaveLength(2)); expect(s.commands[1].op).toBe('post_sj'); expect(s.commands[1].payload).not.toHaveProperty('original_revision_id'); });

test('review remains live under the application StrictMode effect lifecycle',async()=>{const {StrictMode}=await import('react');const s=store();s.rows[0].sold_quantity='70';mount(<StrictMode><Review/></StrictMode>,undefined,true);fireEvent.change(await screen.findByLabelText('Alasan perubahan'),{target:{value:'Strict lifecycle'}});fireEvent.click(screen.getByRole('button',{name:'Tinjau semua dampak'}));await waitFor(()=>expect(s.previewCount).toBe(1));});
test('nested optional attachment keeps dismissal guarded while upload is pending and routes denial to source authority',async()=>{
 const s=store();s.impacts.missing_month=[{report_month:month,reason:'missing',head_id:null,coverage_through_date:null}];const notify=vi.fn();
 function Owner(){const sender=useCOTransactionSender({formScope:'evidence-nested',customerId:customer});return <COCorrectionDialog operation="correct_report" customerId={customer} selectedMonth="2026-08-01" source={{draft_id:draftId,expected_draft_version:'1',expected_customer_version:'1',eligible_set_fingerprint:hash,report_head_id:id(4),original_revision_id:id(5),expected_report_version:'1'}} sender={sender} current={()=>wire.actor} onAccepted={async()=>true} onClose={()=>{}} onAuthorityFailure={notify} returnFocus={null}/>;}
 mount(<Owner/>);fireEvent.change(await screen.findByLabelText('Alasan perubahan'),{target:{value:'Bound source'}});fireEvent.click(screen.getByText('Tinjau semua dampak'));fireEvent.click(await screen.findByText('Lengkapi periode 2026-09'));const refresh=await screen.findByText('Perbarui periode terhadap sumber usulan');await waitFor(()=>expect((refresh as HTMLButtonElement).disabled).toBe(false));fireEvent.click(refresh);await screen.findByLabelText('Pilih lampiran');const base=wire.handler;wire.handler=(n:string,a:any)=>n==='pilot_co_evidence_selection_v1'?Promise.resolve({data:null,error:{code:'42501',message:'Nested evidence denied'}}):base(n,a);
 // Refetch the mounted sidecar at its exact draft/version rather than any current-month shortcut.
 const {act}=await import('@testing-library/react');await act(async()=>{const reads=wire.rpc.mock.calls.filter(([n])=>n==='pilot_co_evidence_selection_v1');expect(reads.at(-1)![1].p_draft_id).toBe(draftId);});
 fireEvent.change(screen.getByLabelText('Pilih lampiran'),{target:{files:[Object.assign(new File(['x'],'a.pdf',{type:'application/pdf'}),{arrayBuffer:async()=>new Uint8Array([1]).buffer})]}});await screen.findByText('a.pdf · belum terpasang');expect((screen.getByText('Kembali ke peninjauan') as HTMLButtonElement).disabled).toBe(true);
 let release:any;const profile=wire.handler;wire.handler=(n:string,a:any)=>n==='pilot_my_profile'?new Promise(resolve=>{release=resolve;}):profile(n,a);fireEvent.click(screen.getByText('Verifikasi dan pasang lampiran'));await waitFor(()=>expect((screen.getByText('Kembali ke sumber') as HTMLButtonElement).disabled).toBe(true));await act(async()=>release({data:null,error:{code:'42501',message:'Nested evidence denied'}}));await waitFor(()=>expect(notify).toHaveBeenCalled());expect(screen.queryByLabelText('Terjual Item 1')).toBeNull();
});
