// @vitest-environment node
import { expect,test,vi } from 'vitest';
import { createEvidenceDownloadHandler } from '../../supabase/functions/co-evidence-download/index';
const id='11111111-1111-4111-8111-111111111111',oid='33333333-3333-4333-8333-333333333333';
const bytes=new TextEncoder().encode('%PDF-1.7\n%%EOF\n');
const config={url:'https://project.example',anonKey:'public',serviceKey:'secret'};
const request=()=>new Request('https://edge.example',{method:'POST',headers:{authorization:'Bearer user','content-type':'application/json'},body:JSON.stringify({evidence_id:id})});
async function ctx(){return {version:'1',id,actor_id:id,bucket:'co-evidence',path:`${id}.pdf`,filename:`evidence-${id}.pdf`,mime_type:'application/pdf',byte_size:bytes.length,sha256:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join(''),state:'finalized',object:{id:oid,version:null}};}
test('reauthorizes after fetch and returns only no-store attachment bytes',async()=>{const c=await ctx();const f=vi.fn(async(u:any)=>String(u).includes('/rpc/')?Response.json(c):new Response(bytes));const response=await createEvidenceDownloadHandler(config,f)(request());expect(response.status).toBe(200);expect(new Uint8Array(await response.arrayBuffer())).toEqual(bytes);expect(response.headers.get('content-disposition')).toBe(`attachment; filename="evidence-${id}.pdf"`);expect(response.headers.get('content-type')).toBe('application/octet-stream');expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(response.headers.get('cache-control')).toBe('no-store');expect(f.mock.calls.filter(([u])=>String(u).includes('/rpc/'))).toHaveLength(2);});
test.each(['downgrade','replacement','digest'])('refuses %s after initial permission',async(kind)=>{const c=await ctx();let count=0;const f=vi.fn(async(u:any)=>{if(String(u).includes('/rpc/')){count++;return kind==='downgrade'&&count>1?Response.json({code:'42501'},{status:403}):Response.json({...c,object:{...c.object,version:kind==='replacement'&&count>1?'changed':null}});}return new Response(kind==='digest'?bytes.slice(0,7):bytes);});const response=await createEvidenceDownloadHandler(config,f)(request());expect(response.status).not.toBe(200);expect(response.headers.has('content-disposition')).toBe(false);});
test('denial never fetches privileged bytes; strict ID-only bounded request',async()=>{const f=vi.fn(async()=>Response.json({code:'42501'},{status:403}));expect((await createEvidenceDownloadHandler(config,f)(request())).status).toBe(403);expect(f).toHaveBeenCalledTimes(1);const req=new Request('https://edge.example',{method:'POST',headers:{authorization:'Bearer user'},body:JSON.stringify({evidence_id:id,path:'arbitrary'})});expect((await createEvidenceDownloadHandler(config,f)(req)).status).toBe(400);expect(f).toHaveBeenCalledTimes(1);});
test.each([{path:'https://evil.example/steal'},{filename:'bad\r\nX-Evil: 1.pdf'},{bucket:'public'},{object:{id:'no',version:null}}])('hostile context fails closed without fetching any storage URL: %j',async(change)=>{const c=await ctx();const f=vi.fn(async()=>Response.json({...c,...change}));const r=await createEvidenceDownloadHandler(config,f)(request());expect(r.status).toBe(502);expect(f).toHaveBeenCalledTimes(1);});
test('lost download response is a fresh authenticated read, never a returned URL',async()=>{const c=await ctx();let fetches=0;const f=vi.fn(async(u:any,o:any)=>{expect(o.redirect).toBe('error');if(String(u).includes('/rpc/'))return Response.json(c);if(++fetches===1)throw new Error('Lost bytes');return new Response(bytes);});expect((await createEvidenceDownloadHandler(config,f)(request())).status).toBe(502);const response=await createEvidenceDownloadHandler(config,f)(request());expect(response.status).toBe(200);expect(new Uint8Array(await response.arrayBuffer())).toEqual(bytes);expect(response.headers.has('location')).toBe(false);expect(fetches).toBe(2);});
