import { expect, test } from 'vitest';
import { screen, fireEvent, waitFor, act } from '@testing-library/react';
import { store, mount, reportImpact, allocation, wire, id, customer, month } from './report-ui-harness';
import COMonthlyReport from '../../src/pages/athel/co/COMonthlyReport';
import COMonthlyReports from '../../src/pages/athel/co/COMonthlyReports';
const click = async (name: string) => fireEvent.click(await screen.findByRole('button', { name }));
test('blank stays unanswered, explicit sold quantity saves via the real sender and review uses stored bindings', async () => { const s = store(); s.impacts.report = [reportImpact()]; s.allocations = [allocation(1, '60', '10000'), allocation(2, '10', '12000')]; mount(<COMonthlyReport />); const input = await screen.findByLabelText('Terjual Item 1'); expect((input as HTMLInputElement).value).toBe(''); fireEvent.change(input, { target: { value: '70' } }); expect(await screen.findByText('Sisa provisional: 30')).toBeTruthy(); await click('Simpan Draft'); await waitFor(() => expect(s.commands).toHaveLength(1)); expect(s.commands[0].payload.lines).toEqual([{ stock_key_id: id(1001), sold_quantity: 70 }]); expect(s.cv).toBe('1'); await click('Tinjau laporan'); expect(await screen.findByText('Pendapatan periode dipilih: Rp 720.000')).toBeTruthy(); expect(screen.getByText(/Seluruh riwayat pelanggan sesudah: Rp 1.720.000/)).toBeTruthy(); await click('Alokasi Item 1'); expect(await screen.findByText(/PIC-1/)).toBeTruthy(); expect(screen.getByText(/PIC-2/)).toBeTruthy(); await click('Post laporan'); await waitFor(() => expect(s.commands.filter((c: any) => c.op === 'post_report')).toHaveLength(1)); expect(Object.keys(s.commands[1].payload).sort()).toEqual(['draft_id', 'eligible_set_fingerprint', 'expected_customer_version', 'expected_draft_version', 'preview_fingerprint']); });
test('bulk zero confirms the complete count including unloaded rows and preserves entered values', async () => { const s = store(601); mount(<COMonthlyReport />); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '7' } }); await click('Isi sisa kosong dengan nol'); expect(await screen.findByText(/600 baris belum diisi, termasuk halaman yang belum dibuka/)).toBeTruthy(); expect(s.commands[0].payload.lines[0].sold_quantity).toBe(7); await click('Konfirmasi nol'); await waitFor(() => expect(s.commands.some((c: any) => c.payload.action === 'fill_remaining_zero')).toBe(true)); expect(s.rows[600].sold_quantity).toBe('0'); expect(s.rows[0].sold_quantity).toBe('7'); expect(s.cv).toBe('1'); });
test('source-context draft retains rows and explicitly returns to original preparation without invented routing', async () => { const s = store(); s.metadata.source_context_link = { operation: 'post_sj', target_id: null, draft_id: id(90), original_revision_id: null, expected_source_version: null, expected_co_version: '1', expected_customer_version: '1', expected_draft_version: '1' }; s.metadata.source_context_fingerprint = 'c'.repeat(64); mount(<COMonthlyReport />); await screen.findByLabelText('Terjual Item 1'); expect(screen.getByText(/Siapkan ulang sumber asli/)).toBeTruthy(); expect(screen.queryByRole('button', { name: 'Tinjau laporan' })).toBeNull(); });
test('reports list applies real customer month and posted filters with revised a badge', async () => { store(); mount(<COMonthlyReports />, `/athel/co/reports?customer=${customer}`); await screen.findByText('Store A'); fireEvent.change(screen.getByLabelText('Status laporan'), { target: { value: 'posted' } }); await waitFor(() => expect(wire.rpc.mock.calls.some(([n, a]) => n === 'pilot_co_reports_page_v1' && a.p_status === 'posted' && a.p_customer_id === customer)).toBe(true)); expect(screen.queryByRole('option', { name: 'Revised' })).toBeNull(); });
test('all 601 stored rows save in sequential 500+101 chunks and post only complete draft bindings', async () => { const s = store(601); s.impacts.report = [{ ...reportImpact(), row_count: '601', after_sold_quantity: '601' }]; mount(<COMonthlyReport />); for (let p = 1; p <= 7; p++) {
    await screen.findByLabelText(`Terjual Item ${(p - 1) * 100 + 1}`);
    for (const input of Array.from(document.querySelectorAll('input[aria-label^="Terjual "]')))
        await act(async () => { fireEvent.change(input, { target: { value: '1' } }); });
    if (p < 7)
        await click('Berikutnya');
} await click('Simpan Draft'); await waitFor(() => expect(s.commands).toHaveLength(2)); await waitFor(() => expect((screen.getByRole('button', { name: 'Tinjau laporan' }) as HTMLButtonElement).disabled).toBe(false)); expect(s.commands.map((c: any) => c.payload.lines.length)).toEqual([500, 101]); expect(s.commands.map((c: any) => c.payload.expected_draft_version)).toEqual(['1', '2']); await click('Tinjau laporan'); await screen.findByRole('button', { name: 'Post laporan' }); await click('Post laporan'); await waitFor(() => expect(s.commands.filter((c: any) => c.op === 'post_report')).toHaveLength(1)); expect(s.rows.every((r: any) => r.sold_quantity === '1')).toBe(true); expect(s.commands[2].payload.expected_draft_version).toBe('3'); }, 60000);
test('new eligibility 602 invalidates review, refresh preserves entered values and leaves the new row blank', async () => { const s = store(601); s.rows.forEach((r: any) => r.sold_quantity = '1'); s.impacts.report = [reportImpact()]; const { client } = mount(<COMonthlyReport />); await screen.findByLabelText('Terjual Item 1'); await click('Tinjau laporan'); await screen.findByRole('button', { name: 'Post laporan' }); s.rows.push({ ...s.rows[0], id: id(1602), stock_key_id: id(1602), display_sku: 'SKU-602', product_name: 'Item 602', sold_quantity: null }); s.cv = '2'; await client.invalidateQueries({ queryKey: ['co'] }); await screen.findByText(/Versi atau sumber berubah/); expect(screen.queryByRole('button', { name: 'Post laporan' })).toBeNull(); await click('Siapkan / perbarui draft'); await waitFor(() => expect((screen.getByRole('button', { name: 'Simpan Draft' }) as HTMLButtonElement).disabled).toBe(false)); for (let p = 1; p < 7; p++)
    await click('Berikutnya'); expect((await screen.findByLabelText('Terjual Item 602') as HTMLInputElement).value).toBe(''); expect(s.rows[0].sold_quantity).toBe('1'); });
test('retained failed row refresh preserves mounted raw fields and freezes every write until retry', async () => { const s = store(); const { client } = mount(<COMonthlyReport />); const input = await screen.findByLabelText('Terjual Item 1'); fireEvent.change(input, { target: { value: '7' } }); s.fail = (n: string) => n === 'pilot_co_report_rows_v1' ? { data: null, error: { code: '08006', message: 'Rows offline' } } : null; await client.invalidateQueries({ queryKey: ['co'] }); await screen.findByText('Rows offline'); expect(screen.getByLabelText('Terjual Item 1')).toBe(input); expect((input as HTMLInputElement).disabled).toBe(true); expect(screen.getByLabelText('Catatan laporan').matches(':disabled')).toBe(true); s.fail = null; fireEvent.click(screen.getByRole('button', { name: 'Coba lagi' })); await waitFor(() => expect((input as HTMLInputElement).disabled).toBe(false)); expect((input as HTMLInputElement).value).toBe('7'); });
test('zero-sales confirmation is based on selected statement even when customer history has sales', async () => { const s = store(); s.rows[0].sold_quantity = '0'; s.impacts.report = [{ ...reportImpact(), after_sold_quantity: '0', after_revenue: '0' }]; const original = s.handle; wire.handler = async (n: string, a: any) => { const r = await original(n, a); if (n === 'pilot_co_preview_v1')
    r.data.after.sold_quantity = '700'; return r; }; mount(<COMonthlyReport />); await screen.findByLabelText('Terjual Item 1'); await click('Tinjau laporan'); await screen.findByRole('button', { name: 'Post laporan' }); await click('Post laporan'); expect(await screen.findByText('Konfirmasi bulan tanpa penjualan')).toBeTruthy(); expect(s.commands).toHaveLength(0); await click('Konfirmasi nol'); await waitFor(() => expect(s.commands).toHaveLength(1)); });
test('a rejected second chunk retains only unsaved entries and retries from the acknowledged version', async () => { const s = store(501); mount(<COMonthlyReport />); for (let p = 1; p <= 6; p++) {
    await screen.findByLabelText(`Terjual Item ${(p - 1) * 100 + 1}`);
    for (const input of Array.from(document.querySelectorAll('input[aria-label^="Terjual "]')))
        await act(async () => { fireEvent.change(input, { target: { value: '2' } }); });
    if (p < 6)
        await click('Berikutnya');
} let rejects = true; s.fail = (n: string, a: any) => n === 'pilot_co_transaction_v1' && a.p_payload.action === 'upsert_lines' && a.p_payload.expected_draft_version === '2' && rejects ? { data: null, error: { code: '22023', message: 'Second chunk rejected' } } : null; await click('Simpan Draft'); await screen.findByText('Second chunk rejected'); expect(s.commands).toHaveLength(1); expect((screen.getByLabelText('Terjual Item 501') as HTMLInputElement).value).toBe('2'); expect(s.rows[499].sold_quantity).toBe('2'); expect(s.rows[500].sold_quantity).toBeNull(); rejects = false; await click('Simpan Draft'); await waitFor(() => expect(s.commands).toHaveLength(2)); expect(s.commands[1].payload.lines).toEqual([{ stock_key_id: id(1501), sold_quantity: 2 }]); expect(s.commands[1].payload.expected_draft_version).toBe('2'); expect(s.cv).toBe('1'); }, 60000);
test.each(['1e2', '-1', '1.5', '2147483648'])('invalid sold %s is retained and never sent as rounded or zero', async (value) => { const s = store(); mount(<COMonthlyReport />); const input = await screen.findByLabelText('Terjual Item 1'); fireEvent.change(input, { target: { value } }); await click('Simpan Draft'); await screen.findByRole('alert'); expect((input as HTMLInputElement).value).toBe(value); expect(s.commands).toHaveLength(0); });
test('navigation and voluntary signout Keep retain dirty report; discard follows destination', async () => { const { act } = await import('@testing-library/react'); store(); const { router } = mount(<COMonthlyReport />); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '3' } }); await act(() => router.navigate('/athel/co')); fireEvent.click(await screen.findByRole('button', { name: 'Tetap mengedit' })); expect((screen.getByLabelText('Terjual Item 1') as HTMLInputElement).value).toBe('3'); let decision!: Promise<boolean>; await act(async () => { decision = wire.guard(new AbortController().signal); }); fireEvent.click(await screen.findByRole('button', { name: 'Tetap mengedit' })); expect(await decision).toBe(false); await act(() => router.navigate('/athel/co')); fireEvent.click(await screen.findByRole('button', { name: 'Buang perubahan' })); await waitFor(() => expect(router.state.location.pathname).toBe('/athel/co')); });
test('forced actor loss during review clears private report input and cannot restore the late result', async () => { const { act } = await import('@testing-library/react'); const s = store(); s.rows[0].sold_quantity = '70'; let release!: (v: any) => void; const base = s.handle; wire.handler = async (n: string, a: any) => n === 'pilot_co_preview_v1' ? new Promise(r => { release = async () => r(await base(n, a)); }) : base(n, a); const { router, client } = mount(<COMonthlyReport />); await screen.findByLabelText('Terjual Item 1'); await click('Tinjau laporan'); await waitFor(() => expect(release).toBeTypeOf('function')); wire.actor = false; await act(() => router.revalidate()); await waitFor(() => expect(screen.queryByLabelText('Terjual Item 1')).toBeNull()); await act(async () => release(null)); expect(screen.queryByRole('button', { name: 'Post laporan' })).toBeNull(); expect(client.getQueryCache().getAll().filter(q => q.queryKey[0] === 'co' && q.state.data)).toHaveLength(0); });
test('canonical read retry after an acknowledged chunk preserves metadata not yet sent', async () => { const s = store(); mount(<COMonthlyReport />); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '70' } }); fireEvent.change(screen.getByLabelText('Catatan laporan'), { target: { value: 'Still unsent' } }); s.fail = (n: string) => n === 'pilot_co_report_v1' && s.commands.length ? { data: null, error: { code: '08006', message: 'Import offline' } } : null; await click('Simpan Draft'); await screen.findByText('Import offline'); expect(s.commands).toHaveLength(1); s.fail = null; await click('Buka hasil laporan tersimpan'); await waitFor(() => expect((screen.getByRole('button', { name: 'Simpan Draft' }) as HTMLButtonElement).disabled).toBe(false)); expect((screen.getByLabelText('Catatan laporan') as HTMLInputElement).value).toBe('Still unsent'); await click('Simpan Draft'); await waitFor(() => expect(s.commands).toHaveLength(2)); expect(s.commands[1].payload).toMatchObject({ action: 'set_metadata', notes: 'Still unsent', expected_draft_version: '2' }); });
test('authoritative row denial clears mounted private fields and cached data', async () => { const s = store(); const { client } = mount(<COMonthlyReport />); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '7' } }); s.fail = (n: string) => n === 'pilot_co_report_rows_v1' ? { data: null, error: { code: '42501', message: 'Authority revoked' } } : null; await client.invalidateQueries({ queryKey: ['co'] }); await screen.findByText('Authority revoked'); expect(screen.queryByLabelText('Terjual Item 1')).toBeNull(); expect(client.getQueryCache().getAll().filter(q => q.queryKey[0] === 'co' && q.state.data)).toHaveLength(0); s.fail = null; fireEvent.click(screen.getByRole('button', { name: 'Coba lagi' })); expect((await screen.findByLabelText('Terjual Item 1') as HTMLInputElement).value).toBe(''); });
test('Save focuses the invalid sold field even when it is on an earlier page', async () => { store(101); mount(<COMonthlyReport />); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '1.5' } }); await click('Berikutnya'); await screen.findByLabelText('Terjual Item 101'); await click('Simpan Draft'); await waitFor(() => expect(document.activeElement?.getAttribute('aria-label')).toBe('Terjual Item 1')); });
test('historical revision evidence uses the explicit checked revision and never labels current rows as original', async () => { const s = store(); s.rows[0].sold_quantity = '7'; s.effective = { ...s.header(), id: id(4), status: 'posted', draft_id: null, draft_version: null, report_head_id: id(4), revision_id: id(5), report_version: '2', eligible_set_fingerprint: null, revenue: '70000' }; s.draft = false; const base = s.handle; wire.handler = async (n: string, a: any) => { const r = await base(n, a); if (n === 'pilot_co_report_rows_v1' && a.p_view === 'revision') {
    r.data.revision_id = a.p_revision_id;
    r.data.rows = [{ ...r.data.rows[0], sold_quantity: '0' }];
} return r; }; mount(<COMonthlyReport />, `/athel/co/reports/${customer}/${month}?revision=${id(6)}`); expect(await screen.findByText(`Bukti revisi historis ${id(6)}`)).toBeTruthy(); expect(wire.rpc.mock.calls.some(([n, a]) => n === 'pilot_co_report_rows_v1' && a.p_view === 'revision' && a.p_revision_id === id(6))).toBe(true); });
test('stale final fingerprint keeps input and never auto-reposts', async () => { const s = store(); s.rows[0].sold_quantity = '70'; s.impacts.report = [reportImpact()]; mount(<COMonthlyReport />); await screen.findByLabelText('Terjual Item 1'); await click('Tinjau laporan'); await screen.findByRole('button', { name: 'Post laporan' }); s.fail = (n: string, a: any) => n === 'pilot_co_transaction_v1' && a.p_operation === 'post_report' ? { data: null, error: { code: 'PT409', message: 'Preview changed' } } : null; await click('Post laporan'); await screen.findByText(/CO berubah/); expect((screen.getByLabelText('Terjual Item 1') as HTMLInputElement).value).toBe('70'); expect(s.commands).toHaveLength(0); expect(screen.queryByRole('button', { name: 'Post laporan' })).toBeNull(); });
test('role replacement drops staged values and a delayed review cannot reinstate the old fingerprint', async () => { const s = store(); s.rows[0].sold_quantity = '70'; let resolve!: (value: any) => void; const base = s.handle; wire.handler = async (n: string, a: any) => n === 'pilot_co_preview_v1' ? new Promise(r => { resolve = async () => r(await base(n, a)); }) : base(n, a); const { router } = mount(<COMonthlyReport />); await screen.findByLabelText('Terjual Item 1'); await click('Tinjau laporan'); await waitFor(() => expect(resolve).toBeTypeOf('function')); wire.role = 'executive'; await act(() => router.revalidate()); await screen.findByLabelText('Terjual Item 1'); await act(async () => resolve(null)); expect(screen.queryByRole('button', { name: 'Post laporan' })).toBeNull(); expect(s.commands).toHaveLength(0); });
test('refresh freezes raw inputs until canonical hydration finishes', async () => { const s = store(); s.rows[0].sold_quantity = '70'; const { client } = mount(<COMonthlyReport />); const input = await screen.findByLabelText('Terjual Item 1'); s.cv = '2'; await client.invalidateQueries({ queryKey: ['co'] }); await screen.findByText(/Versi atau sumber berubah/); let finish!: (value: any) => void; s.fail = (n: string) => n === 'pilot_co_report_v1' ? new Promise(r => { finish = () => r(null); }) : null; await click('Siapkan / perbarui draft'); await waitFor(() => expect(finish).toBeTypeOf('function')); expect((input as HTMLInputElement).disabled).toBe(true); fireEvent.change(input, { target: { value: '99' } }); s.fail = null; await act(async () => finish(null)); await waitFor(() => expect((screen.getByRole('button', { name: 'Simpan Draft' }) as HTMLButtonElement).disabled).toBe(false)); expect((screen.getByLabelText('Terjual Item 1') as HTMLInputElement).value).toBe('70'); });
test('authority denial stops automatic private reads until an explicit retry', async () => { const s = store(); const { client } = mount(<COMonthlyReport />); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '9' } }); let deniedReads = 0; s.fail = (n: string) => { if (n === 'pilot_co_report_v1') {
    deniedReads++;
    return { data: null, error: { code: '42501', message: 'Report access denied' } };
} return null; }; await client.invalidateQueries({ queryKey: ['co'] }); await screen.findByText('Report access denied'); await act(async () => new Promise(r => setTimeout(r, 50))); expect(deniedReads).toBe(1); expect(screen.queryByLabelText('Terjual Item 1')).toBeNull(); s.fail = null; fireEvent.click(screen.getByRole('button', { name: 'Coba lagi' })); expect((await screen.findByLabelText('Terjual Item 1') as HTMLInputElement).value).toBe(''); });
test('Review saves staged input and leaves the newly bound preview available in one action', async () => { const s = store(); s.impacts.report = [reportImpact()]; mount(<COMonthlyReport />); fireEvent.change(await screen.findByLabelText('Terjual Item 1'), { target: { value: '70' } }); await click('Tinjau laporan'); expect(await screen.findByRole('button', { name: 'Post laporan' })).toBeTruthy(); expect(s.commands).toHaveLength(1); const preview = wire.rpc.mock.calls.find(([n]) => n === 'pilot_co_preview_v1')![1]; expect(preview.p_payload.expected_draft_version).toBe('2'); });

test('same-version context diagnostics freeze the saved editor rather than trusting its old ready header',async()=>{const s=store();const {client}=mount(<COMonthlyReport/>);fireEvent.change(await screen.findByLabelText('Terjual Item 1'),{target:{value:'7'}});s.metadata.context_issue='CO_ELIGIBLE_SET_STALE';await client.invalidateQueries({predicate:q=>q.queryKey[4]==='report'});await waitFor(()=>expect((screen.getByRole('button',{name:'Simpan Draft'}) as HTMLButtonElement).disabled).toBe(true));expect((screen.getByLabelText('Terjual Item 1') as HTMLInputElement).value).toBe('7');});
