import { transferableAbortController } from 'node:util'
import { useState } from 'react'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createMemoryRouter, RouterProvider, Routes, Route } from 'react-router-dom'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
const state=vi.hoisted(()=>({callback:null as any,signOut:vi.fn(),role:'co_admin',id:'actor-a',active:true}))
vi.mock('../../src/lib/supabase',()=>({supabase:{auth:{getSession:async()=>({data:{session:{user:{id:state.id}}}}),onAuthStateChange:(callback:any)=>{state.callback=callback;return{data:{subscription:{unsubscribe:vi.fn()}}}},signOut:()=>state.signOut()},rpc:()=>({single:async()=>({data:{id:state.id,role:state.role,is_active:state.active,full_name:'Operator'},error:null})})}}))
import { AuthProvider, useAuth, useBeforeSignOut } from '../../src/lib/AuthContext'
import { useUnsavedChanges } from '../../src/lib/useUnsavedChanges'
import ProtectedRoute from '../../src/components/ProtectedRoute'
import AthelNav from '../../src/components/AthelNav'
let client:QueryClient, router:ReturnType<typeof createMemoryRouter>, editorGeneration=0, guardCalls=0, currentAuth:ReturnType<typeof useAuth>
function EditorGuard({guard,generation}:{guard:(signal:AbortSignal)=>Promise<boolean>;generation:number}){useBeforeSignOut(guard,generation);return null}
function Editor(){currentAuth=useAuth();const [draft,setDraft]=useState('unsaved');const [generation,setGeneration]=useState(editorGeneration);const [registered,setRegistered]=useState(true);const unsaved=useUnsavedChanges(!!draft);

 return <>{registered&&<EditorGuard generation={generation} guard={signal=>{guardCalls++;return unsaved.confirmDiscardDecision({signal})}}/>}<AthelNav/><input aria-label="Editor" value={draft} onChange={e=>setDraft(e.target.value)}/><button onClick={()=>setGeneration(v=>v+1)}>Replace editor</button><button onClick={()=>setRegistered(false)}>Unregister</button>{unsaved.dialog}</>
}
function Tree(){return <Routes><Route path="/editor" element={<ProtectedRoute><Editor/></ProtectedRoute>}/><Route path="/login" element={<p>Logged out</p>}/></Routes>}
async function mount(){router=createMemoryRouter([{path:'*',element:<QueryClientProvider client={client}><AuthProvider><Tree/></AuthProvider></QueryClientProvider>}],{initialEntries:['/editor']});render(<RouterProvider router={router}/>);await screen.findByLabelText('Editor');await act(async()=>{});client.setQueryData(['private'],{secret:'fixture'});fireEvent.click(screen.getByRole('button',{name:'Menu pengguna'}));await screen.findByRole('button',{name:'Keluar'})}
function logout(){fireEvent.click(screen.getByRole('button',{name:'Keluar'}))}
beforeEach(()=>{vi.stubGlobal('AbortController',class { constructor(){return transferableAbortController()} });state.id='actor-a';state.role='co_admin';state.active=true;state.signOut.mockReset().mockResolvedValue({error:null});guardCalls=0;editorGeneration=0;client=new QueryClient({defaultOptions:{queries:{retry:false}}})})
afterEach(()=>{cleanup();router?.dispose();client.clear();vi.unstubAllGlobals()})
test('Keep never calls auth or clears cache/editor and repeated clicks coalesce',async()=>{await mount();const button=screen.getByRole('button',{name:'Keluar'});fireEvent.click(button);fireEvent.click(button);await screen.findByRole('dialog');expect(guardCalls).toBe(1);expect(state.signOut).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Tetap mengedit'}));expect((screen.getByLabelText('Editor')as HTMLInputElement).value).toBe('unsaved');expect(client.getQueryData(['private'])).toEqual({secret:'fixture'});expect(state.signOut).not.toHaveBeenCalled();expect(router.state.location.pathname).toBe('/editor')})
test('accepted signout makes one auth call and one auth-driven redirect without another dialog',async()=>{await mount();logout();fireEvent.click(await screen.findByRole('button',{name:'Buang perubahan'}));await screen.findByText('Logged out');expect(state.signOut).toHaveBeenCalledOnce();expect(client.getQueryData(['private'])).toBeUndefined();expect(screen.queryByRole('dialog')).toBeNull();expect(router.state.location.pathname).toBe('/login')})
test('failed signout leaves verified editor intact and re-arms confirmation',async()=>{state.signOut.mockResolvedValue({error:new Error('offline')});await mount();logout();fireEvent.click(await screen.findByRole('button',{name:'Buang perubahan'}));await screen.findByText('Tidak dapat keluar. Silakan coba lagi.');expect((screen.getByLabelText('Editor')as HTMLInputElement).value).toBe('unsaved');expect(client.getQueryData(['private'])).toEqual({secret:'fixture'});logout();await screen.findByRole('dialog');expect(guardCalls).toBe(2);expect(state.signOut).toHaveBeenCalledOnce()})
test.each(['Replace editor','Unregister'])('stale accepted decision cannot execute after %s',async name=>{await mount();logout();await screen.findByRole('dialog');fireEvent.click(screen.getByRole('button',{name}));const discard=screen.queryByRole('button',{name:'Buang perubahan'});if(discard)fireEvent.click(discard);await act(async()=>{});expect(state.signOut).not.toHaveBeenCalled();expect(screen.getByLabelText('Editor')).toBeTruthy()})
test('forced signout immediately clears while a dirty decision is open',async()=>{await mount();logout();await screen.findByRole('dialog');await act(async()=>state.callback('SIGNED_OUT',null));await screen.findByText('Logged out');expect(screen.queryByRole('dialog')).toBeNull();expect(client.getQueryData(['private'])).toBeUndefined();expect(state.signOut).not.toHaveBeenCalled()})
test('late auth failure never restores a forced signed-out identity',async()=>{let finish:any;state.signOut.mockImplementation(()=>new Promise(resolve=>{finish=resolve}));await mount();logout();fireEvent.click(await screen.findByRole('button',{name:'Buang perubahan'}));await waitFor(()=>expect(state.signOut).toHaveBeenCalledOnce());await act(async()=>state.callback('SIGNED_OUT',null));await screen.findByText('Logged out');await act(async()=>finish({error:new Error('late failure')}));expect(screen.queryByLabelText('Editor')).toBeNull();expect(client.getQueryData(['private'])).toBeUndefined()})
test('old confirmation cannot sign out a newly authenticated actor',async()=>{await mount();logout();await screen.findByRole('dialog');state.id='actor-b';await act(async()=>state.callback('SIGNED_IN',{user:{id:state.id}}));await screen.findByLabelText('Editor');expect(state.signOut).not.toHaveBeenCalled();expect(screen.queryByRole('dialog')).toBeNull();expect(client.getQueryData(['private'])).toBeUndefined()})
test('a late successful logout does not clear a newly verified actor cache',async()=>{let finish:any;state.signOut.mockImplementation(()=>new Promise(resolve=>{finish=resolve}));await mount();logout();fireEvent.click(await screen.findByRole('button',{name:'Buang perubahan'}));await waitFor(()=>expect(state.signOut).toHaveBeenCalledOnce());state.id='actor-b';await act(async()=>state.callback('SIGNED_IN',{user:{id:state.id}}));await screen.findByLabelText('Editor');client.setQueryData(['new-actor'],{owner:'b'});await act(async()=>finish({error:null}));expect(screen.getByLabelText('Editor')).toBeTruthy();expect(client.getQueryData(['new-actor'])).toEqual({owner:'b'});expect(router.state.location.pathname).toBe('/editor')})

test('direct duplicate requests share one disposition and Escape keeps editing',async()=>{await mount();let first!:Promise<boolean>,second!:Promise<boolean>;act(()=>{first=currentAuth.signOut();second=currentAuth.signOut()});expect(first).toBe(second);const dialog=await screen.findByRole('dialog');fireEvent(dialog,new Event('cancel',{bubbles:true,cancelable:true}));await expect(first).resolves.toBe(false);expect(state.signOut).not.toHaveBeenCalled();expect(client.getQueryData(['private'])).toEqual({secret:'fixture'})})
test('profile deactivation aborts confirmation and immediately drops authority',async()=>{await mount();logout();await screen.findByRole('dialog');state.active=false;await act(async()=>state.callback('TOKEN_REFRESHED',{user:{id:state.id}}));await screen.findByText('Logged out');expect(screen.queryByRole('dialog')).toBeNull();expect(client.getQueryData(['private'])).toBeUndefined();expect(state.signOut).not.toHaveBeenCalled()})
test('role replacement cancels its old editor confirmation and private cache',async()=>{await mount();logout();await screen.findByRole('dialog');state.role='po_admin';await act(async()=>state.callback('TOKEN_REFRESHED',{user:{id:state.id}}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(client.getQueryData(['private'])).toBeUndefined();expect(state.signOut).not.toHaveBeenCalled();logout();await screen.findByRole('dialog');expect(guardCalls).toBe(2)})
